# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cym/prj2/finn/notebooks/icl_thesis-master/vivado/transformer_overlay/transformer_overlay.srcs/sources_1/bd/transformer_design/ip/transformer_design_auto_us_0/transformer_design_auto_us_0.xci
# IP: The module: 'transformer_design_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cym/prj2/finn/notebooks/icl_thesis-master/vivado/transformer_overlay/transformer_overlay.gen/sources_1/bd/transformer_design/ip/transformer_design_auto_us_0/transformer_design_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'transformer_design_auto_us_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/cym/prj2/finn/notebooks/icl_thesis-master/vivado/transformer_overlay/transformer_overlay.gen/sources_1/bd/transformer_design/ip/transformer_design_auto_us_0/transformer_design_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'transformer_design_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/cym/prj2/finn/notebooks/icl_thesis-master/vivado/transformer_overlay/transformer_overlay.srcs/sources_1/bd/transformer_design/ip/transformer_design_auto_us_0/transformer_design_auto_us_0.xci
# IP: The module: 'transformer_design_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cym/prj2/finn/notebooks/icl_thesis-master/vivado/transformer_overlay/transformer_overlay.gen/sources_1/bd/transformer_design/ip/transformer_design_auto_us_0/transformer_design_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'transformer_design_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/cym/prj2/finn/notebooks/icl_thesis-master/vivado/transformer_overlay/transformer_overlay.gen/sources_1/bd/transformer_design/ip/transformer_design_auto_us_0/transformer_design_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'transformer_design_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
