// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module unsw_linear_transformer_layer_norm_1d_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_6_0_0_0_Pipeline_VITIS_LO_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        sext_ln1348,
        variance_V_4_out,
        variance_V_4_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] input_r_address0;
output   input_r_ce0;
input  [15:0] input_r_q0;
input  [15:0] sext_ln1348;
output  [23:0] variance_V_4_out;
output   variance_V_4_out_ap_vld;

reg ap_idle;
reg input_r_ce0;
reg variance_V_4_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln59_fu_137_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [16:0] sext_ln1348_cast_fu_120_p1;
reg  signed [16:0] sext_ln1348_cast_reg_474;
reg   [0:0] icmp_ln59_reg_479;
reg   [0:0] icmp_ln59_reg_479_pp0_iter1_reg;
reg   [0:0] icmp_ln59_reg_479_pp0_iter2_reg;
wire   [15:0] select_ln302_fu_214_p3;
reg   [15:0] select_ln302_reg_488;
wire   [39:0] r_V_5_fu_233_p2;
reg   [39:0] r_V_5_reg_493;
reg   [0:0] tmp_1596_reg_498;
wire   [39:0] ret_V_2_fu_262_p2;
reg   [39:0] ret_V_2_reg_503;
reg   [0:0] p_Result_136_reg_509;
wire   [23:0] variance_V_4_fu_296_p2;
reg   [23:0] variance_V_4_reg_515;
wire   [0:0] p_Result_138_fu_302_p3;
reg   [0:0] p_Result_138_reg_520;
wire   [0:0] xor_ln896_68_fu_310_p2;
reg   [0:0] xor_ln896_68_reg_525;
wire   [0:0] carry_27_fu_316_p2;
reg   [0:0] carry_27_reg_530;
wire   [0:0] Range1_all_ones_fu_332_p2;
reg   [0:0] Range1_all_ones_reg_537;
wire   [0:0] Range1_all_zeros_fu_338_p2;
reg   [0:0] Range1_all_zeros_reg_544;
wire   [63:0] feature_3_cast_fu_149_p1;
wire    ap_block_pp0_stage0;
reg   [23:0] lhs_V_fu_86;
wire   [23:0] variance_V_fu_443_p3;
reg   [23:0] ap_sig_allocacmp_lhs_V_load_1;
wire    ap_loop_init;
reg   [4:0] feature_3_fu_90;
wire   [4:0] add_ln59_fu_143_p2;
reg   [4:0] ap_sig_allocacmp_feature;
wire    ap_block_pp0_stage0_01001;
wire  signed [16:0] sext_ln1348_3_fu_159_p1;
wire   [16:0] ret_V_fu_163_p2;
wire   [0:0] p_Result_s_fu_168_p3;
wire   [0:0] p_Result_135_fu_180_p3;
wire   [0:0] xor_ln895_66_fu_188_p2;
wire   [0:0] overflow_fu_194_p2;
wire   [0:0] xor_ln302_7_fu_200_p2;
wire   [15:0] select_ln346_fu_206_p3;
wire   [15:0] centered_V_fu_176_p1;
wire   [19:0] r_V_fu_222_p3;
wire  signed [19:0] r_V_5_fu_233_p0;
wire  signed [39:0] sext_ln1270_fu_229_p1;
wire  signed [19:0] r_V_5_fu_233_p1;
wire   [37:0] lhs_V_2_fu_250_p3;
wire  signed [39:0] sext_ln1347_fu_258_p1;
wire   [23:0] zext_ln377_fu_293_p1;
wire   [23:0] variance_V_3_fu_275_p4;
wire   [0:0] p_Result_137_fu_285_p3;
wire   [1:0] tmp_fu_322_p4;
wire   [0:0] tmp_1599_fu_356_p3;
wire   [0:0] Range2_all_ones_fu_344_p3;
wire   [0:0] xor_ln890_fu_363_p2;
wire   [0:0] and_ln890_28_fu_369_p2;
wire   [0:0] deleted_zeros_fu_351_p3;
wire   [0:0] xor_ln895_69_fu_385_p2;
wire   [0:0] or_ln895_29_fu_391_p2;
wire   [0:0] xor_ln895_70_fu_396_p2;
wire   [0:0] deleted_ones_14_fu_375_p3;
wire   [0:0] xor_ln896_70_fu_407_p2;
wire   [0:0] and_ln891_28_fu_381_p2;
wire   [0:0] or_ln896_29_fu_413_p2;
wire   [0:0] xor_ln896_fu_418_p2;
wire   [0:0] overflow_11_fu_401_p2;
wire   [0:0] underflow_fu_424_p2;
wire   [0:0] or_ln346_fu_437_p2;
wire   [23:0] select_ln346_402_fu_429_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

unsw_linear_transformer_mul_20s_20s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 20 ),
    .dout_WIDTH( 40 ))
mul_20s_20s_40_1_1_U463(
    .din0(r_V_5_fu_233_p0),
    .din1(r_V_5_fu_233_p1),
    .dout(r_V_5_fu_233_p2)
);

unsw_linear_transformer_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln59_fu_137_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            feature_3_fu_90 <= add_ln59_fu_143_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            feature_3_fu_90 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            lhs_V_fu_86 <= 24'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            lhs_V_fu_86 <= variance_V_fu_443_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Range1_all_ones_reg_537 <= Range1_all_ones_fu_332_p2;
        Range1_all_zeros_reg_544 <= Range1_all_zeros_fu_338_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        carry_27_reg_530 <= carry_27_fu_316_p2;
        icmp_ln59_reg_479_pp0_iter2_reg <= icmp_ln59_reg_479_pp0_iter1_reg;
        p_Result_136_reg_509 <= ret_V_2_fu_262_p2[32'd39];
        p_Result_138_reg_520 <= variance_V_4_fu_296_p2[32'd23];
        r_V_5_reg_493 <= r_V_5_fu_233_p2;
        ret_V_2_reg_503 <= ret_V_2_fu_262_p2;
        tmp_1596_reg_498 <= r_V_5_fu_233_p2[32'd13];
        variance_V_4_reg_515 <= variance_V_4_fu_296_p2;
        xor_ln896_68_reg_525 <= xor_ln896_68_fu_310_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln59_reg_479 <= icmp_ln59_fu_137_p2;
        icmp_ln59_reg_479_pp0_iter1_reg <= icmp_ln59_reg_479;
        select_ln302_reg_488 <= select_ln302_fu_214_p3;
        sext_ln1348_cast_reg_474 <= sext_ln1348_cast_fu_120_p1;
    end
end

always @ (*) begin
    if (((icmp_ln59_fu_137_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_feature = 5'd0;
    end else begin
        ap_sig_allocacmp_feature = feature_3_fu_90;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_sig_allocacmp_lhs_V_load_1 = variance_V_fu_443_p3;
    end else begin
        ap_sig_allocacmp_lhs_V_load_1 = lhs_V_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln59_reg_479_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        variance_V_4_out_ap_vld = 1'b1;
    end else begin
        variance_V_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Range1_all_ones_fu_332_p2 = ((tmp_fu_322_p4 == 2'd3) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_338_p2 = ((tmp_fu_322_p4 == 2'd0) ? 1'b1 : 1'b0);

assign Range2_all_ones_fu_344_p3 = ret_V_2_reg_503[32'd39];

assign add_ln59_fu_143_p2 = (ap_sig_allocacmp_feature + 5'd1);

assign and_ln890_28_fu_369_p2 = (xor_ln890_fu_363_p2 & Range2_all_ones_fu_344_p3);

assign and_ln891_28_fu_381_p2 = (carry_27_reg_530 & Range1_all_ones_reg_537);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign carry_27_fu_316_p2 = (xor_ln896_68_fu_310_p2 & p_Result_137_fu_285_p3);

assign centered_V_fu_176_p1 = ret_V_fu_163_p2[15:0];

assign deleted_ones_14_fu_375_p3 = ((carry_27_reg_530[0:0] == 1'b1) ? and_ln890_28_fu_369_p2 : Range1_all_ones_reg_537);

assign deleted_zeros_fu_351_p3 = ((carry_27_reg_530[0:0] == 1'b1) ? Range1_all_ones_reg_537 : Range1_all_zeros_reg_544);

assign feature_3_cast_fu_149_p1 = ap_sig_allocacmp_feature;

assign icmp_ln59_fu_137_p2 = ((ap_sig_allocacmp_feature == 5'd16) ? 1'b1 : 1'b0);

assign input_r_address0 = feature_3_cast_fu_149_p1;

assign lhs_V_2_fu_250_p3 = {{ap_sig_allocacmp_lhs_V_load_1}, {14'd0}};

assign or_ln346_fu_437_p2 = (underflow_fu_424_p2 | overflow_11_fu_401_p2);

assign or_ln895_29_fu_391_p2 = (xor_ln895_69_fu_385_p2 | p_Result_138_reg_520);

assign or_ln896_29_fu_413_p2 = (xor_ln896_70_fu_407_p2 | xor_ln896_68_reg_525);

assign overflow_11_fu_401_p2 = (xor_ln895_70_fu_396_p2 & or_ln895_29_fu_391_p2);

assign overflow_fu_194_p2 = (xor_ln895_66_fu_188_p2 & p_Result_135_fu_180_p3);

assign p_Result_135_fu_180_p3 = ret_V_fu_163_p2[32'd15];

assign p_Result_137_fu_285_p3 = ret_V_2_fu_262_p2[32'd37];

assign p_Result_138_fu_302_p3 = variance_V_4_fu_296_p2[32'd23];

assign p_Result_s_fu_168_p3 = ret_V_fu_163_p2[32'd16];

assign r_V_5_fu_233_p0 = sext_ln1270_fu_229_p1;

assign r_V_5_fu_233_p1 = sext_ln1270_fu_229_p1;

assign r_V_fu_222_p3 = {{select_ln302_reg_488}, {4'd0}};

assign ret_V_2_fu_262_p2 = ($signed(sext_ln1347_fu_258_p1) + $signed(r_V_5_reg_493));

assign ret_V_fu_163_p2 = ($signed(sext_ln1348_3_fu_159_p1) - $signed(sext_ln1348_cast_reg_474));

assign select_ln302_fu_214_p3 = ((xor_ln302_7_fu_200_p2[0:0] == 1'b1) ? select_ln346_fu_206_p3 : centered_V_fu_176_p1);

assign select_ln346_402_fu_429_p3 = ((overflow_11_fu_401_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln346_fu_206_p3 = ((overflow_fu_194_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign sext_ln1270_fu_229_p1 = $signed(r_V_fu_222_p3);

assign sext_ln1347_fu_258_p1 = $signed(lhs_V_2_fu_250_p3);

assign sext_ln1348_3_fu_159_p1 = $signed(input_r_q0);

assign sext_ln1348_cast_fu_120_p1 = $signed(sext_ln1348);

assign tmp_1599_fu_356_p3 = ret_V_2_reg_503[32'd38];

assign tmp_fu_322_p4 = {{ret_V_2_fu_262_p2[39:38]}};

assign underflow_fu_424_p2 = (xor_ln896_fu_418_p2 & p_Result_136_reg_509);

assign variance_V_3_fu_275_p4 = {{ret_V_2_fu_262_p2[37:14]}};

assign variance_V_4_fu_296_p2 = (zext_ln377_fu_293_p1 + variance_V_3_fu_275_p4);

assign variance_V_4_out = lhs_V_fu_86;

assign variance_V_fu_443_p3 = ((or_ln346_fu_437_p2[0:0] == 1'b1) ? select_ln346_402_fu_429_p3 : variance_V_4_reg_515);

assign xor_ln302_7_fu_200_p2 = (p_Result_s_fu_168_p3 ^ p_Result_135_fu_180_p3);

assign xor_ln890_fu_363_p2 = (tmp_1599_fu_356_p3 ^ 1'd1);

assign xor_ln895_66_fu_188_p2 = (p_Result_s_fu_168_p3 ^ 1'd1);

assign xor_ln895_69_fu_385_p2 = (deleted_zeros_fu_351_p3 ^ 1'd1);

assign xor_ln895_70_fu_396_p2 = (p_Result_136_reg_509 ^ 1'd1);

assign xor_ln896_68_fu_310_p2 = (p_Result_138_fu_302_p3 ^ 1'd1);

assign xor_ln896_70_fu_407_p2 = (deleted_ones_14_fu_375_p3 ^ 1'd1);

assign xor_ln896_fu_418_p2 = (or_ln896_29_fu_413_p2 ^ and_ln891_28_fu_381_p2);

assign zext_ln377_fu_293_p1 = tmp_1596_reg_498;

endmodule //unsw_linear_transformer_layer_norm_1d_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_6_0_0_0_Pipeline_VITIS_LO_1
