-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity unsw_linear_transformer_layer_norm_1d_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_6_0_0_0_Pipeline_VITIS_LO_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    sext_ln1348 : IN STD_LOGIC_VECTOR (15 downto 0);
    variance_V_8_out : OUT STD_LOGIC_VECTOR (23 downto 0);
    variance_V_8_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of unsw_linear_transformer_layer_norm_1d_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_6_0_0_0_Pipeline_VITIS_LO_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv24_7FFFFF : STD_LOGIC_VECTOR (23 downto 0) := "011111111111111111111111";
    constant ap_const_lv24_800000 : STD_LOGIC_VECTOR (23 downto 0) := "100000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln63_fu_137_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal sext_ln1348_cast_fu_120_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1348_cast_reg_478 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln63_reg_483 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln302_fu_214_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln302_reg_492 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal r_V_24_fu_233_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal r_V_24_reg_497 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal tmp_186_reg_502 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_6_fu_262_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal ret_V_6_reg_507 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal p_Result_195_reg_513 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_196_reg_519 : STD_LOGIC_VECTOR (0 downto 0);
    signal variance_V_8_fu_296_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal variance_V_8_reg_524 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Result_197_reg_529 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_535 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal zext_ln63_fu_149_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal lhs_V_fu_86 : STD_LOGIC_VECTOR (23 downto 0);
    signal variance_V_fu_447_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal feature_6_fu_90 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln63_fu_143_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_feature : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal sext_ln1348_3_fu_159_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ret_V_fu_163_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Result_s_fu_168_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_194_fu_180_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln302_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_fu_206_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal centered_V_fu_176_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal r_V_fu_222_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal r_V_24_fu_233_p0 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln1270_fu_229_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal r_V_24_fu_233_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal lhs_V_4_fu_250_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln1347_fu_258_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal zext_ln377_fu_293_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal variance_V_7_fu_275_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal xor_ln896_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_52_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_189_fu_355_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_fu_330_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln890_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln890_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_347_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_35_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln895_fu_394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_36_fu_399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_33_fu_374_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln896_48_fu_410_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln891_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln896_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln896_49_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_31_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln346_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_39_fu_433_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component unsw_linear_transformer_mul_20s_20s_40_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (19 downto 0);
        din1 : IN STD_LOGIC_VECTOR (19 downto 0);
        dout : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;


    component unsw_linear_transformer_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_20s_20s_40_1_1_U118 : component unsw_linear_transformer_mul_20s_20s_40_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 20,
        din1_WIDTH => 20,
        dout_WIDTH => 40)
    port map (
        din0 => r_V_24_fu_233_p0,
        din1 => r_V_24_fu_233_p1,
        dout => r_V_24_fu_233_p2);

    flow_control_loop_pipe_sequential_init_U : component unsw_linear_transformer_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    feature_6_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln63_fu_137_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    feature_6_fu_90 <= add_ln63_fu_143_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    feature_6_fu_90 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_V_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    lhs_V_fu_86 <= ap_const_lv24_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    lhs_V_fu_86 <= variance_V_fu_447_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln63_reg_483 <= icmp_ln63_fu_137_p2;
                sext_ln1348_cast_reg_478 <= sext_ln1348_cast_fu_120_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln63_reg_483 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                p_Result_195_reg_513 <= ret_V_6_fu_262_p2(39 downto 39);
                p_Result_196_reg_519 <= ret_V_6_fu_262_p2(37 downto 37);
                p_Result_197_reg_529 <= variance_V_8_fu_296_p2(23 downto 23);
                ret_V_6_reg_507 <= ret_V_6_fu_262_p2;
                tmp_reg_535 <= ret_V_6_fu_262_p2(39 downto 38);
                variance_V_8_reg_524 <= variance_V_8_fu_296_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln63_reg_483 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                r_V_24_reg_497 <= r_V_24_fu_233_p2;
                tmp_186_reg_502 <= r_V_24_fu_233_p2(13 downto 13);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln63_reg_483 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                select_ln302_reg_492 <= select_ln302_fu_214_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter0_stage0, ap_block_pp0_stage3_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    Range1_all_ones_fu_337_p2 <= "1" when (tmp_reg_535 = ap_const_lv2_3) else "0";
    Range1_all_zeros_fu_342_p2 <= "1" when (tmp_reg_535 = ap_const_lv2_0) else "0";
    Range2_all_ones_fu_330_p3 <= ret_V_6_reg_507(39 downto 39);
    add_ln63_fu_143_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_feature) + unsigned(ap_const_lv5_1));
    and_ln890_fu_368_p2 <= (xor_ln890_fu_362_p2 and Range2_all_ones_fu_330_p3);
    and_ln891_fu_382_p2 <= (carry_52_fu_325_p2 and Range1_all_ones_fu_337_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage3_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln63_fu_137_p2)
    begin
        if (((icmp_ln63_fu_137_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_feature_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, feature_6_fu_90)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_feature <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_feature <= feature_6_fu_90;
        end if; 
    end process;

    carry_52_fu_325_p2 <= (xor_ln896_fu_320_p2 and p_Result_196_reg_519);
    centered_V_fu_176_p1 <= ret_V_fu_163_p2(16 - 1 downto 0);
    deleted_ones_33_fu_374_p3 <= 
        and_ln890_fu_368_p2 when (carry_52_fu_325_p2(0) = '1') else 
        Range1_all_ones_fu_337_p2;
    deleted_zeros_fu_347_p3 <= 
        Range1_all_ones_fu_337_p2 when (carry_52_fu_325_p2(0) = '1') else 
        Range1_all_zeros_fu_342_p2;
    icmp_ln63_fu_137_p2 <= "1" when (ap_sig_allocacmp_feature = ap_const_lv5_10) else "0";
    input_r_address0 <= zext_ln63_fu_149_p1(4 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    lhs_V_4_fu_250_p3 <= (lhs_V_fu_86 & ap_const_lv14_0);
    or_ln346_fu_441_p2 <= (underflow_fu_428_p2 or overflow_31_fu_404_p2);
    or_ln895_fu_394_p2 <= (xor_ln895_35_fu_388_p2 or p_Result_197_reg_529);
    or_ln896_fu_416_p2 <= (xor_ln896_fu_320_p2 or xor_ln896_48_fu_410_p2);
    overflow_31_fu_404_p2 <= (xor_ln895_36_fu_399_p2 and or_ln895_fu_394_p2);
    overflow_fu_194_p2 <= (xor_ln895_fu_188_p2 and p_Result_194_fu_180_p3);
    p_Result_194_fu_180_p3 <= ret_V_fu_163_p2(15 downto 15);
    p_Result_s_fu_168_p3 <= ret_V_fu_163_p2(16 downto 16);
    r_V_24_fu_233_p0 <= sext_ln1270_fu_229_p1(20 - 1 downto 0);
    r_V_24_fu_233_p1 <= sext_ln1270_fu_229_p1(20 - 1 downto 0);
    r_V_fu_222_p3 <= (select_ln302_reg_492 & ap_const_lv4_0);
    ret_V_6_fu_262_p2 <= std_logic_vector(signed(sext_ln1347_fu_258_p1) + signed(r_V_24_reg_497));
    ret_V_fu_163_p2 <= std_logic_vector(signed(sext_ln1348_3_fu_159_p1) - signed(sext_ln1348_cast_reg_478));
    select_ln302_fu_214_p3 <= 
        select_ln346_fu_206_p3 when (xor_ln302_fu_200_p2(0) = '1') else 
        centered_V_fu_176_p1;
    select_ln346_39_fu_433_p3 <= 
        ap_const_lv24_7FFFFF when (overflow_31_fu_404_p2(0) = '1') else 
        ap_const_lv24_800000;
    select_ln346_fu_206_p3 <= 
        ap_const_lv16_7FFF when (overflow_fu_194_p2(0) = '1') else 
        ap_const_lv16_8000;
        sext_ln1270_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_fu_222_p3),40));

        sext_ln1347_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(lhs_V_4_fu_250_p3),40));

        sext_ln1348_3_fu_159_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(input_r_q0),17));

        sext_ln1348_cast_fu_120_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1348),17));

    tmp_189_fu_355_p3 <= ret_V_6_reg_507(38 downto 38);
    underflow_fu_428_p2 <= (xor_ln896_49_fu_422_p2 and p_Result_195_reg_513);
    variance_V_7_fu_275_p4 <= ret_V_6_fu_262_p2(37 downto 14);
    variance_V_8_fu_296_p2 <= std_logic_vector(unsigned(zext_ln377_fu_293_p1) + unsigned(variance_V_7_fu_275_p4));
    variance_V_8_out <= lhs_V_fu_86;

    variance_V_8_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln63_fu_137_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln63_fu_137_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            variance_V_8_out_ap_vld <= ap_const_logic_1;
        else 
            variance_V_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    variance_V_fu_447_p3 <= 
        select_ln346_39_fu_433_p3 when (or_ln346_fu_441_p2(0) = '1') else 
        variance_V_8_reg_524;
    xor_ln302_fu_200_p2 <= (p_Result_s_fu_168_p3 xor p_Result_194_fu_180_p3);
    xor_ln890_fu_362_p2 <= (tmp_189_fu_355_p3 xor ap_const_lv1_1);
    xor_ln895_35_fu_388_p2 <= (deleted_zeros_fu_347_p3 xor ap_const_lv1_1);
    xor_ln895_36_fu_399_p2 <= (p_Result_195_reg_513 xor ap_const_lv1_1);
    xor_ln895_fu_188_p2 <= (p_Result_s_fu_168_p3 xor ap_const_lv1_1);
    xor_ln896_48_fu_410_p2 <= (deleted_ones_33_fu_374_p3 xor ap_const_lv1_1);
    xor_ln896_49_fu_422_p2 <= (or_ln896_fu_416_p2 xor and_ln891_fu_382_p2);
    xor_ln896_fu_320_p2 <= (p_Result_197_reg_529 xor ap_const_lv1_1);
    zext_ln377_fu_293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_186_reg_502),24));
    zext_ln63_fu_149_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_feature),64));
end behav;
