// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        values_new_address0,
        values_new_ce0,
        values_new_q0,
        values_new_address1,
        values_new_ce1,
        values_new_q1,
        front_address0,
        front_ce0,
        front_q0,
        attn_residual_address0,
        attn_residual_ce0,
        attn_residual_we0,
        attn_residual_d0,
        grp_fu_2070_p_din0,
        grp_fu_2070_p_din1,
        grp_fu_2070_p_opcode,
        grp_fu_2070_p_dout0,
        grp_fu_2070_p_ce,
        grp_fu_2074_p_din0,
        grp_fu_2074_p_din1,
        grp_fu_2074_p_opcode,
        grp_fu_2074_p_dout0,
        grp_fu_2074_p_ce,
        grp_fu_2082_p_din0,
        grp_fu_2082_p_din1,
        grp_fu_2082_p_opcode,
        grp_fu_2082_p_dout0,
        grp_fu_2082_p_ce,
        grp_fu_2078_p_din0,
        grp_fu_2078_p_din1,
        grp_fu_2078_p_dout0,
        grp_fu_2078_p_ce,
        grp_fu_2146_p_din0,
        grp_fu_2146_p_din1,
        grp_fu_2146_p_dout0,
        grp_fu_2146_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] values_new_address0;
output   values_new_ce0;
input  [31:0] values_new_q0;
output  [5:0] values_new_address1;
output   values_new_ce1;
input  [31:0] values_new_q1;
output  [5:0] front_address0;
output   front_ce0;
input  [31:0] front_q0;
output  [5:0] attn_residual_address0;
output   attn_residual_ce0;
output   attn_residual_we0;
output  [31:0] attn_residual_d0;
output  [31:0] grp_fu_2070_p_din0;
output  [31:0] grp_fu_2070_p_din1;
output  [1:0] grp_fu_2070_p_opcode;
input  [31:0] grp_fu_2070_p_dout0;
output   grp_fu_2070_p_ce;
output  [31:0] grp_fu_2074_p_din0;
output  [31:0] grp_fu_2074_p_din1;
output  [1:0] grp_fu_2074_p_opcode;
input  [31:0] grp_fu_2074_p_dout0;
output   grp_fu_2074_p_ce;
output  [31:0] grp_fu_2082_p_din0;
output  [31:0] grp_fu_2082_p_din1;
output  [1:0] grp_fu_2082_p_opcode;
input  [31:0] grp_fu_2082_p_dout0;
output   grp_fu_2082_p_ce;
output  [31:0] grp_fu_2078_p_din0;
output  [31:0] grp_fu_2078_p_din1;
input  [31:0] grp_fu_2078_p_dout0;
output   grp_fu_2078_p_ce;
output  [31:0] grp_fu_2146_p_din0;
output  [31:0] grp_fu_2146_p_din1;
input  [31:0] grp_fu_2146_p_dout0;
output   grp_fu_2146_p_ce;

reg ap_idle;
reg[5:0] values_new_address0;
reg values_new_ce0;
reg[5:0] values_new_address1;
reg values_new_ce1;
reg front_ce0;
reg attn_residual_ce0;
reg attn_residual_we0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state8_pp0_stage3_iter1;
wire    ap_block_state12_pp0_stage3_iter2;
wire    ap_block_state16_pp0_stage3_iter3;
wire    ap_block_state20_pp0_stage3_iter4;
wire    ap_block_state24_pp0_stage3_iter5;
wire    ap_block_state28_pp0_stage3_iter6;
wire    ap_block_state32_pp0_stage3_iter7;
wire    ap_block_state36_pp0_stage3_iter8;
wire    ap_block_state40_pp0_stage3_iter9;
wire    ap_block_state44_pp0_stage3_iter10;
wire    ap_block_state48_pp0_stage3_iter11;
wire    ap_block_state52_pp0_stage3_iter12;
wire    ap_block_state56_pp0_stage3_iter13;
wire    ap_block_pp0_stage3_subdone;
reg   [0:0] icmp_ln143_reg_567;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_address0;
reg    TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_ce0;
wire   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_q0;
wire   [2:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_address0;
reg    TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_ce0;
wire   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_q0;
wire   [2:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_address0;
reg    TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_ce0;
wire   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_q0;
wire   [2:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_address0;
reg    TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_ce0;
wire   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_q0;
wire   [2:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_address0;
reg    TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_ce0;
wire   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_q0;
wire   [2:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_address0;
reg    TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_ce0;
wire   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_q0;
wire   [2:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_address0;
reg    TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_ce0;
wire   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_q0;
wire   [2:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_address0;
reg    TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_ce0;
wire   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_q0;
wire   [2:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_address0;
reg    TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_ce0;
wire   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_q0;
reg   [3:0] i_2_reg_562;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state9_pp0_stage0_iter2;
wire    ap_block_state13_pp0_stage0_iter3;
wire    ap_block_state17_pp0_stage0_iter4;
wire    ap_block_state21_pp0_stage0_iter5;
wire    ap_block_state25_pp0_stage0_iter6;
wire    ap_block_state29_pp0_stage0_iter7;
wire    ap_block_state33_pp0_stage0_iter8;
wire    ap_block_state37_pp0_stage0_iter9;
wire    ap_block_state41_pp0_stage0_iter10;
wire    ap_block_state45_pp0_stage0_iter11;
wire    ap_block_state49_pp0_stage0_iter12;
wire    ap_block_state53_pp0_stage0_iter13;
wire    ap_block_state57_pp0_stage0_iter14;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln143_fu_360_p2;
reg   [0:0] icmp_ln143_reg_567_pp0_iter1_reg;
reg   [0:0] icmp_ln143_reg_567_pp0_iter2_reg;
reg   [0:0] icmp_ln143_reg_567_pp0_iter3_reg;
reg   [0:0] icmp_ln143_reg_567_pp0_iter4_reg;
reg   [0:0] icmp_ln143_reg_567_pp0_iter5_reg;
reg   [0:0] icmp_ln143_reg_567_pp0_iter6_reg;
reg   [0:0] icmp_ln143_reg_567_pp0_iter7_reg;
reg   [0:0] icmp_ln143_reg_567_pp0_iter8_reg;
reg   [0:0] icmp_ln143_reg_567_pp0_iter9_reg;
reg   [0:0] icmp_ln143_reg_567_pp0_iter10_reg;
reg   [0:0] icmp_ln143_reg_567_pp0_iter11_reg;
reg   [0:0] icmp_ln143_reg_567_pp0_iter12_reg;
wire   [0:0] icmp_ln145_fu_375_p2;
reg   [0:0] icmp_ln145_reg_571;
wire   [3:0] select_ln143_fu_381_p3;
reg   [3:0] select_ln143_reg_576;
wire   [3:0] add_ln143_1_fu_389_p2;
reg   [3:0] add_ln143_1_reg_582;
wire   [5:0] select_ln143_1_fu_407_p3;
reg   [5:0] select_ln143_1_reg_587;
wire   [63:0] j_5_cast30_fu_431_p1;
reg   [63:0] j_5_cast30_reg_608;
reg   [63:0] j_5_cast30_reg_608_pp0_iter1_reg;
reg   [63:0] j_5_cast30_reg_608_pp0_iter2_reg;
reg   [63:0] j_5_cast30_reg_608_pp0_iter3_reg;
reg   [63:0] j_5_cast30_reg_608_pp0_iter4_reg;
reg   [63:0] j_5_cast30_reg_608_pp0_iter5_reg;
reg   [63:0] j_5_cast30_reg_608_pp0_iter6_reg;
reg   [63:0] j_5_cast30_reg_608_pp0_iter7_reg;
reg   [63:0] j_5_cast30_reg_608_pp0_iter8_reg;
reg   [63:0] j_5_cast30_reg_608_pp0_iter9_reg;
reg   [63:0] j_5_cast30_reg_608_pp0_iter10_reg;
reg   [31:0] values_new_load_reg_653;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state6_pp0_stage1_iter1;
wire    ap_block_state10_pp0_stage1_iter2;
wire    ap_block_state14_pp0_stage1_iter3;
wire    ap_block_state18_pp0_stage1_iter4;
wire    ap_block_state22_pp0_stage1_iter5;
wire    ap_block_state26_pp0_stage1_iter6;
wire    ap_block_state30_pp0_stage1_iter7;
wire    ap_block_state34_pp0_stage1_iter8;
wire    ap_block_state38_pp0_stage1_iter9;
wire    ap_block_state42_pp0_stage1_iter10;
wire    ap_block_state46_pp0_stage1_iter11;
wire    ap_block_state50_pp0_stage1_iter12;
wire    ap_block_state54_pp0_stage1_iter13;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] values_new_load_1_reg_658;
reg   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_load_reg_673;
reg   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_load_reg_678;
reg   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_load_reg_683;
reg   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_load_reg_688;
reg   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_load_reg_693;
reg   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_load_reg_698;
reg   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_load_reg_703;
reg   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_load_reg_708;
wire   [63:0] zext_ln46_fu_476_p1;
reg   [63:0] zext_ln46_reg_713;
reg   [63:0] zext_ln46_reg_713_pp0_iter1_reg;
reg   [63:0] zext_ln46_reg_713_pp0_iter2_reg;
reg   [63:0] zext_ln46_reg_713_pp0_iter3_reg;
reg   [63:0] zext_ln46_reg_713_pp0_iter4_reg;
reg   [63:0] zext_ln46_reg_713_pp0_iter5_reg;
reg   [63:0] zext_ln46_reg_713_pp0_iter6_reg;
reg   [63:0] zext_ln46_reg_713_pp0_iter7_reg;
reg   [63:0] zext_ln46_reg_713_pp0_iter8_reg;
reg   [63:0] zext_ln46_reg_713_pp0_iter9_reg;
reg   [63:0] zext_ln46_reg_713_pp0_iter10_reg;
reg   [63:0] zext_ln46_reg_713_pp0_iter11_reg;
reg   [63:0] zext_ln46_reg_713_pp0_iter12_reg;
reg   [63:0] zext_ln46_reg_713_pp0_iter13_reg;
reg   [31:0] values_new_load_2_reg_723;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state7_pp0_stage2_iter1;
wire    ap_block_state11_pp0_stage2_iter2;
wire    ap_block_state15_pp0_stage2_iter3;
wire    ap_block_state19_pp0_stage2_iter4;
wire    ap_block_state23_pp0_stage2_iter5;
wire    ap_block_state27_pp0_stage2_iter6;
wire    ap_block_state31_pp0_stage2_iter7;
wire    ap_block_state35_pp0_stage2_iter8;
wire    ap_block_state39_pp0_stage2_iter9;
wire    ap_block_state43_pp0_stage2_iter10;
wire    ap_block_state47_pp0_stage2_iter11;
wire    ap_block_state51_pp0_stage2_iter12;
wire    ap_block_state55_pp0_stage2_iter13;
wire    ap_block_pp0_stage2_11001;
reg   [31:0] values_new_load_3_reg_728;
reg   [31:0] front_load_reg_743;
reg   [31:0] front_load_reg_743_pp0_iter1_reg;
reg   [31:0] front_load_reg_743_pp0_iter2_reg;
reg   [31:0] front_load_reg_743_pp0_iter3_reg;
reg   [31:0] front_load_reg_743_pp0_iter4_reg;
reg   [31:0] front_load_reg_743_pp0_iter5_reg;
reg   [31:0] front_load_reg_743_pp0_iter6_reg;
reg   [31:0] front_load_reg_743_pp0_iter7_reg;
reg   [31:0] front_load_reg_743_pp0_iter8_reg;
reg   [31:0] front_load_reg_743_pp0_iter9_reg;
reg   [31:0] front_load_reg_743_pp0_iter10_reg;
reg   [31:0] front_load_reg_743_pp0_iter11_reg;
reg   [31:0] front_load_reg_743_pp0_iter12_reg;
reg   [31:0] values_new_load_4_reg_748;
wire    ap_block_pp0_stage3_11001;
reg   [31:0] values_new_load_5_reg_753;
reg   [31:0] values_new_load_6_reg_768;
reg   [31:0] values_new_load_7_reg_773;
reg   [31:0] mul8_reg_778;
reg   [31:0] mul8_1_reg_783;
reg   [31:0] mul8_1_reg_783_pp0_iter2_reg;
reg   [31:0] mul8_2_reg_788;
reg   [31:0] mul8_2_reg_788_pp0_iter2_reg;
reg   [31:0] mul8_2_reg_788_pp0_iter3_reg;
reg   [31:0] mul8_3_reg_793;
reg   [31:0] mul8_3_reg_793_pp0_iter2_reg;
reg   [31:0] mul8_3_reg_793_pp0_iter3_reg;
reg   [31:0] mul8_3_reg_793_pp0_iter4_reg;
reg   [31:0] mul8_4_reg_798;
reg   [31:0] mul8_4_reg_798_pp0_iter2_reg;
reg   [31:0] mul8_4_reg_798_pp0_iter3_reg;
reg   [31:0] mul8_4_reg_798_pp0_iter4_reg;
reg   [31:0] mul8_4_reg_798_pp0_iter5_reg;
reg   [31:0] mul8_5_reg_803;
reg   [31:0] mul8_5_reg_803_pp0_iter2_reg;
reg   [31:0] mul8_5_reg_803_pp0_iter3_reg;
reg   [31:0] mul8_5_reg_803_pp0_iter4_reg;
reg   [31:0] mul8_5_reg_803_pp0_iter5_reg;
reg   [31:0] mul8_5_reg_803_pp0_iter6_reg;
reg   [31:0] mul8_6_reg_808;
reg   [31:0] mul8_6_reg_808_pp0_iter3_reg;
reg   [31:0] mul8_6_reg_808_pp0_iter4_reg;
reg   [31:0] mul8_6_reg_808_pp0_iter5_reg;
reg   [31:0] mul8_6_reg_808_pp0_iter6_reg;
reg   [31:0] mul8_6_reg_808_pp0_iter7_reg;
reg   [31:0] mul8_6_reg_808_pp0_iter8_reg;
reg   [31:0] mul8_7_reg_813;
reg   [31:0] mul8_7_reg_813_pp0_iter3_reg;
reg   [31:0] mul8_7_reg_813_pp0_iter4_reg;
reg   [31:0] mul8_7_reg_813_pp0_iter5_reg;
reg   [31:0] mul8_7_reg_813_pp0_iter6_reg;
reg   [31:0] mul8_7_reg_813_pp0_iter7_reg;
reg   [31:0] mul8_7_reg_813_pp0_iter8_reg;
reg   [31:0] mul8_7_reg_813_pp0_iter9_reg;
reg   [31:0] mul8_7_reg_813_pp0_iter10_reg;
reg   [31:0] sum_s_reg_818;
reg   [31:0] sum_11_1_reg_823;
reg   [31:0] sum_11_2_reg_828;
reg   [31:0] sum_11_3_reg_833;
reg   [31:0] sum_11_4_reg_838;
reg   [31:0] sum_11_5_reg_843;
reg   [31:0] sum_11_6_reg_848;
reg   [31:0] sum_11_7_reg_858;
reg   [31:0] TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_load_reg_863;
reg   [31:0] o_proj_reg_868;
reg   [31:0] add1_reg_873;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln143_fu_415_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln143_1_fu_426_p1;
wire   [63:0] zext_ln143_2_fu_453_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln143_3_fu_463_p1;
wire   [63:0] zext_ln143_4_fu_486_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln143_5_fu_496_p1;
wire   [63:0] zext_ln143_6_fu_506_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln143_7_fu_516_p1;
reg   [3:0] j_fu_78;
wire   [3:0] add_ln145_fu_526_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_load;
reg   [3:0] i_fu_82;
wire   [3:0] select_ln143_2_fu_521_p3;
reg   [3:0] ap_sig_allocacmp_i_2;
reg   [6:0] indvar_flatten65_fu_86;
wire   [6:0] add_ln143_fu_366_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten65_load;
reg   [31:0] grp_fu_306_p0;
reg   [31:0] grp_fu_306_p1;
reg   [31:0] grp_fu_311_p0;
reg   [31:0] grp_fu_311_p1;
reg   [31:0] grp_fu_315_p0;
reg   [31:0] grp_fu_315_p1;
reg   [31:0] grp_fu_319_p0;
reg   [31:0] grp_fu_319_p1;
reg   [31:0] grp_fu_323_p0;
reg   [31:0] grp_fu_323_p1;
wire   [2:0] empty_fu_348_p1;
wire   [2:0] empty_32_fu_395_p1;
wire   [5:0] p_mid4_fu_399_p3;
wire   [5:0] tmp_s_fu_352_p3;
wire   [5:0] or_ln143_fu_420_p2;
wire   [5:0] or_ln143_1_fu_448_p2;
wire   [5:0] or_ln143_2_fu_458_p2;
wire   [5:0] j_5_cast_fu_468_p1;
wire   [5:0] add_ln152_fu_471_p2;
wire   [5:0] or_ln143_3_fu_481_p2;
wire   [5:0] or_ln143_4_fu_491_p2;
wire   [5:0] or_ln143_5_fu_501_p2;
wire   [5:0] or_ln143_6_fu_511_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter13_stage0;
reg    ap_idle_pp0_0to12;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0_1to14;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage3_00001;
wire    ap_block_pp0_stage0_00001;
wire    ap_block_pp0_stage1_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_CeG #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_address0),
    .ce0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_ce0),
    .q0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_q0)
);

transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_DeQ #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_address0),
    .ce0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_ce0),
    .q0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_q0)
);

transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_Ee0 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_address0),
    .ce0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_ce0),
    .q0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_q0)
);

transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_Ffa #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_address0),
    .ce0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_ce0),
    .q0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_q0)
);

transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_Gfk #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_address0),
    .ce0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_ce0),
    .q0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_q0)
);

transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_Hfu #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_address0),
    .ce0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_ce0),
    .q0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_q0)
);

transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_IfE #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_address0),
    .ce0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_ce0),
    .q0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_q0)
);

transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_JfO #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_address0),
    .ce0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_ce0),
    .q0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_q0)
);

transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_KfY #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_address0),
    .ce0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_ce0),
    .q0(TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_q0)
);

transformer_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter14 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_82 <= 4'd0;
    end else if (((icmp_ln143_reg_567 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        i_fu_82 <= select_ln143_2_fu_521_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln143_fu_360_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten65_fu_86 <= add_ln143_fu_366_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten65_fu_86 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_fu_78 <= 4'd0;
    end else if (((icmp_ln143_reg_567 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        j_fu_78 <= add_ln145_fu_526_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_load_reg_863 <= TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_q0;
        mul8_1_reg_783_pp0_iter2_reg <= mul8_1_reg_783;
        zext_ln46_reg_713_pp0_iter10_reg[5 : 0] <= zext_ln46_reg_713_pp0_iter9_reg[5 : 0];
        zext_ln46_reg_713_pp0_iter11_reg[5 : 0] <= zext_ln46_reg_713_pp0_iter10_reg[5 : 0];
        zext_ln46_reg_713_pp0_iter12_reg[5 : 0] <= zext_ln46_reg_713_pp0_iter11_reg[5 : 0];
        zext_ln46_reg_713_pp0_iter13_reg[5 : 0] <= zext_ln46_reg_713_pp0_iter12_reg[5 : 0];
        zext_ln46_reg_713_pp0_iter1_reg[5 : 0] <= zext_ln46_reg_713[5 : 0];
        zext_ln46_reg_713_pp0_iter2_reg[5 : 0] <= zext_ln46_reg_713_pp0_iter1_reg[5 : 0];
        zext_ln46_reg_713_pp0_iter3_reg[5 : 0] <= zext_ln46_reg_713_pp0_iter2_reg[5 : 0];
        zext_ln46_reg_713_pp0_iter4_reg[5 : 0] <= zext_ln46_reg_713_pp0_iter3_reg[5 : 0];
        zext_ln46_reg_713_pp0_iter5_reg[5 : 0] <= zext_ln46_reg_713_pp0_iter4_reg[5 : 0];
        zext_ln46_reg_713_pp0_iter6_reg[5 : 0] <= zext_ln46_reg_713_pp0_iter5_reg[5 : 0];
        zext_ln46_reg_713_pp0_iter7_reg[5 : 0] <= zext_ln46_reg_713_pp0_iter6_reg[5 : 0];
        zext_ln46_reg_713_pp0_iter8_reg[5 : 0] <= zext_ln46_reg_713_pp0_iter7_reg[5 : 0];
        zext_ln46_reg_713_pp0_iter9_reg[5 : 0] <= zext_ln46_reg_713_pp0_iter8_reg[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln143_reg_567 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_load_reg_673 <= TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_q0;
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_load_reg_678 <= TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_q0;
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_load_reg_683 <= TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_q0;
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_load_reg_688 <= TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_q0;
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_load_reg_693 <= TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_q0;
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_load_reg_698 <= TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_q0;
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_load_reg_703 <= TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_q0;
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_load_reg_708 <= TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_q0;
        zext_ln46_reg_713[5 : 0] <= zext_ln46_fu_476_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add1_reg_873 <= grp_fu_2082_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln143_fu_360_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln143_1_reg_582 <= add_ln143_1_fu_389_p2;
        icmp_ln145_reg_571 <= icmp_ln145_fu_375_p2;
        j_5_cast30_reg_608[3 : 0] <= j_5_cast30_fu_431_p1[3 : 0];
        select_ln143_1_reg_587[5 : 3] <= select_ln143_1_fu_407_p3[5 : 3];
        select_ln143_reg_576 <= select_ln143_fu_381_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln143_reg_567 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        front_load_reg_743 <= front_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        front_load_reg_743_pp0_iter10_reg <= front_load_reg_743_pp0_iter9_reg;
        front_load_reg_743_pp0_iter11_reg <= front_load_reg_743_pp0_iter10_reg;
        front_load_reg_743_pp0_iter12_reg <= front_load_reg_743_pp0_iter11_reg;
        front_load_reg_743_pp0_iter1_reg <= front_load_reg_743;
        front_load_reg_743_pp0_iter2_reg <= front_load_reg_743_pp0_iter1_reg;
        front_load_reg_743_pp0_iter3_reg <= front_load_reg_743_pp0_iter2_reg;
        front_load_reg_743_pp0_iter4_reg <= front_load_reg_743_pp0_iter3_reg;
        front_load_reg_743_pp0_iter5_reg <= front_load_reg_743_pp0_iter4_reg;
        front_load_reg_743_pp0_iter6_reg <= front_load_reg_743_pp0_iter5_reg;
        front_load_reg_743_pp0_iter7_reg <= front_load_reg_743_pp0_iter6_reg;
        front_load_reg_743_pp0_iter8_reg <= front_load_reg_743_pp0_iter7_reg;
        front_load_reg_743_pp0_iter9_reg <= front_load_reg_743_pp0_iter8_reg;
        mul8_2_reg_788_pp0_iter2_reg <= mul8_2_reg_788;
        mul8_2_reg_788_pp0_iter3_reg <= mul8_2_reg_788_pp0_iter2_reg;
        mul8_3_reg_793_pp0_iter2_reg <= mul8_3_reg_793;
        mul8_3_reg_793_pp0_iter3_reg <= mul8_3_reg_793_pp0_iter2_reg;
        mul8_3_reg_793_pp0_iter4_reg <= mul8_3_reg_793_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_2_reg_562 <= ap_sig_allocacmp_i_2;
        icmp_ln143_reg_567 <= icmp_ln143_fu_360_p2;
        icmp_ln143_reg_567_pp0_iter10_reg <= icmp_ln143_reg_567_pp0_iter9_reg;
        icmp_ln143_reg_567_pp0_iter11_reg <= icmp_ln143_reg_567_pp0_iter10_reg;
        icmp_ln143_reg_567_pp0_iter12_reg <= icmp_ln143_reg_567_pp0_iter11_reg;
        icmp_ln143_reg_567_pp0_iter1_reg <= icmp_ln143_reg_567;
        icmp_ln143_reg_567_pp0_iter2_reg <= icmp_ln143_reg_567_pp0_iter1_reg;
        icmp_ln143_reg_567_pp0_iter3_reg <= icmp_ln143_reg_567_pp0_iter2_reg;
        icmp_ln143_reg_567_pp0_iter4_reg <= icmp_ln143_reg_567_pp0_iter3_reg;
        icmp_ln143_reg_567_pp0_iter5_reg <= icmp_ln143_reg_567_pp0_iter4_reg;
        icmp_ln143_reg_567_pp0_iter6_reg <= icmp_ln143_reg_567_pp0_iter5_reg;
        icmp_ln143_reg_567_pp0_iter7_reg <= icmp_ln143_reg_567_pp0_iter6_reg;
        icmp_ln143_reg_567_pp0_iter8_reg <= icmp_ln143_reg_567_pp0_iter7_reg;
        icmp_ln143_reg_567_pp0_iter9_reg <= icmp_ln143_reg_567_pp0_iter8_reg;
        j_5_cast30_reg_608_pp0_iter10_reg[3 : 0] <= j_5_cast30_reg_608_pp0_iter9_reg[3 : 0];
        j_5_cast30_reg_608_pp0_iter1_reg[3 : 0] <= j_5_cast30_reg_608[3 : 0];
        j_5_cast30_reg_608_pp0_iter2_reg[3 : 0] <= j_5_cast30_reg_608_pp0_iter1_reg[3 : 0];
        j_5_cast30_reg_608_pp0_iter3_reg[3 : 0] <= j_5_cast30_reg_608_pp0_iter2_reg[3 : 0];
        j_5_cast30_reg_608_pp0_iter4_reg[3 : 0] <= j_5_cast30_reg_608_pp0_iter3_reg[3 : 0];
        j_5_cast30_reg_608_pp0_iter5_reg[3 : 0] <= j_5_cast30_reg_608_pp0_iter4_reg[3 : 0];
        j_5_cast30_reg_608_pp0_iter6_reg[3 : 0] <= j_5_cast30_reg_608_pp0_iter5_reg[3 : 0];
        j_5_cast30_reg_608_pp0_iter7_reg[3 : 0] <= j_5_cast30_reg_608_pp0_iter6_reg[3 : 0];
        j_5_cast30_reg_608_pp0_iter8_reg[3 : 0] <= j_5_cast30_reg_608_pp0_iter7_reg[3 : 0];
        j_5_cast30_reg_608_pp0_iter9_reg[3 : 0] <= j_5_cast30_reg_608_pp0_iter8_reg[3 : 0];
        mul8_6_reg_808_pp0_iter3_reg <= mul8_6_reg_808;
        mul8_6_reg_808_pp0_iter4_reg <= mul8_6_reg_808_pp0_iter3_reg;
        mul8_6_reg_808_pp0_iter5_reg <= mul8_6_reg_808_pp0_iter4_reg;
        mul8_6_reg_808_pp0_iter6_reg <= mul8_6_reg_808_pp0_iter5_reg;
        mul8_6_reg_808_pp0_iter7_reg <= mul8_6_reg_808_pp0_iter6_reg;
        mul8_6_reg_808_pp0_iter8_reg <= mul8_6_reg_808_pp0_iter7_reg;
        mul8_7_reg_813_pp0_iter10_reg <= mul8_7_reg_813_pp0_iter9_reg;
        mul8_7_reg_813_pp0_iter3_reg <= mul8_7_reg_813;
        mul8_7_reg_813_pp0_iter4_reg <= mul8_7_reg_813_pp0_iter3_reg;
        mul8_7_reg_813_pp0_iter5_reg <= mul8_7_reg_813_pp0_iter4_reg;
        mul8_7_reg_813_pp0_iter6_reg <= mul8_7_reg_813_pp0_iter5_reg;
        mul8_7_reg_813_pp0_iter7_reg <= mul8_7_reg_813_pp0_iter6_reg;
        mul8_7_reg_813_pp0_iter8_reg <= mul8_7_reg_813_pp0_iter7_reg;
        mul8_7_reg_813_pp0_iter9_reg <= mul8_7_reg_813_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul8_1_reg_783 <= grp_fu_2146_p_dout0;
        mul8_reg_778 <= grp_fu_2078_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul8_2_reg_788 <= grp_fu_2078_p_dout0;
        mul8_3_reg_793 <= grp_fu_2146_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul8_4_reg_798 <= grp_fu_2078_p_dout0;
        mul8_5_reg_803 <= grp_fu_2146_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul8_4_reg_798_pp0_iter2_reg <= mul8_4_reg_798;
        mul8_4_reg_798_pp0_iter3_reg <= mul8_4_reg_798_pp0_iter2_reg;
        mul8_4_reg_798_pp0_iter4_reg <= mul8_4_reg_798_pp0_iter3_reg;
        mul8_4_reg_798_pp0_iter5_reg <= mul8_4_reg_798_pp0_iter4_reg;
        mul8_5_reg_803_pp0_iter2_reg <= mul8_5_reg_803;
        mul8_5_reg_803_pp0_iter3_reg <= mul8_5_reg_803_pp0_iter2_reg;
        mul8_5_reg_803_pp0_iter4_reg <= mul8_5_reg_803_pp0_iter3_reg;
        mul8_5_reg_803_pp0_iter5_reg <= mul8_5_reg_803_pp0_iter4_reg;
        mul8_5_reg_803_pp0_iter6_reg <= mul8_5_reg_803_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul8_6_reg_808 <= grp_fu_2078_p_dout0;
        mul8_7_reg_813 <= grp_fu_2146_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        o_proj_reg_868 <= grp_fu_2082_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        sum_11_1_reg_823 <= grp_fu_2070_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_11_2_reg_828 <= grp_fu_2070_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sum_11_3_reg_833 <= grp_fu_2070_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sum_11_4_reg_838 <= grp_fu_2074_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        sum_11_5_reg_843 <= grp_fu_2074_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_11_6_reg_848 <= grp_fu_2074_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        sum_11_7_reg_858 <= grp_fu_2074_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sum_s_reg_818 <= grp_fu_2070_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln143_reg_567 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        values_new_load_1_reg_658 <= values_new_q0;
        values_new_load_reg_653 <= values_new_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln143_reg_567 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        values_new_load_2_reg_723 <= values_new_q1;
        values_new_load_3_reg_728 <= values_new_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln143_reg_567 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        values_new_load_4_reg_748 <= values_new_q1;
        values_new_load_5_reg_753 <= values_new_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        values_new_load_6_reg_768 <= values_new_q1;
        values_new_load_7_reg_773 <= values_new_q0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_ce0 = 1'b1;
    end else begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_ce0 = 1'b1;
    end else begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_ce0 = 1'b1;
    end else begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_ce0 = 1'b1;
    end else begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_ce0 = 1'b1;
    end else begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_ce0 = 1'b1;
    end else begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_ce0 = 1'b1;
    end else begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_ce0 = 1'b1;
    end else begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_ce0 = 1'b1;
    end else begin
        TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln143_reg_567 == 1'd1) & (1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter13 == 1'b1) & (icmp_ln143_reg_567_pp0_iter12_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter13_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter13_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to12 = 1'b1;
    end else begin
        ap_idle_pp0_0to12 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to14 = 1'b1;
    end else begin
        ap_idle_pp0_1to14 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten65_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten65_load = indvar_flatten65_fu_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        attn_residual_ce0 = 1'b1;
    end else begin
        attn_residual_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        attn_residual_we0 = 1'b1;
    end else begin
        attn_residual_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        front_ce0 = 1'b1;
    end else begin
        front_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_306_p0 = sum_11_2_reg_828;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_306_p0 = sum_11_1_reg_823;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_306_p0 = sum_s_reg_818;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_306_p0 = mul8_reg_778;
    end else begin
        grp_fu_306_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_306_p1 = mul8_3_reg_793_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_306_p1 = mul8_2_reg_788_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_306_p1 = mul8_1_reg_783_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_306_p1 = 32'd0;
    end else begin
        grp_fu_306_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_311_p0 = sum_11_6_reg_848;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_311_p0 = sum_11_5_reg_843;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_311_p0 = sum_11_4_reg_838;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_311_p0 = sum_11_3_reg_833;
    end else begin
        grp_fu_311_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_311_p1 = mul8_7_reg_813_pp0_iter10_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_311_p1 = mul8_6_reg_808_pp0_iter8_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_311_p1 = mul8_5_reg_803_pp0_iter6_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_311_p1 = mul8_4_reg_798_pp0_iter5_reg;
    end else begin
        grp_fu_311_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_315_p0 = front_load_reg_743_pp0_iter12_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_315_p0 = sum_11_7_reg_858;
    end else begin
        grp_fu_315_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_315_p1 = o_proj_reg_868;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_315_p1 = TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_load_reg_863;
    end else begin
        grp_fu_315_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_319_p0 = values_new_load_6_reg_768;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_319_p0 = values_new_load_4_reg_748;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_319_p0 = values_new_load_2_reg_723;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_319_p0 = values_new_load_reg_653;
    end else begin
        grp_fu_319_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_319_p1 = TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_load_reg_703;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_319_p1 = TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_load_reg_693;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_319_p1 = TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_load_reg_683;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_319_p1 = TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_load_reg_673;
    end else begin
        grp_fu_319_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_323_p0 = values_new_load_7_reg_773;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_323_p0 = values_new_load_5_reg_753;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_323_p0 = values_new_load_3_reg_728;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_323_p0 = values_new_load_1_reg_658;
    end else begin
        grp_fu_323_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_323_p1 = TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_load_reg_708;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_323_p1 = TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_load_reg_698;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_323_p1 = TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_load_reg_688;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_323_p1 = TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_load_reg_678;
    end else begin
        grp_fu_323_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            values_new_address0 = zext_ln143_7_fu_516_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            values_new_address0 = zext_ln143_5_fu_496_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            values_new_address0 = zext_ln143_3_fu_463_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            values_new_address0 = zext_ln143_1_fu_426_p1;
        end else begin
            values_new_address0 = 'bx;
        end
    end else begin
        values_new_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            values_new_address1 = zext_ln143_6_fu_506_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            values_new_address1 = zext_ln143_4_fu_486_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            values_new_address1 = zext_ln143_2_fu_453_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            values_new_address1 = zext_ln143_fu_415_p1;
        end else begin
            values_new_address1 = 'bx;
        end
    end else begin
        values_new_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        values_new_ce0 = 1'b1;
    end else begin
        values_new_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        values_new_ce1 = 1'b1;
    end else begin
        values_new_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to14 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_BIAS_address0 = j_5_cast30_reg_608_pp0_iter10_reg;

assign TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_0_address0 = j_5_cast30_fu_431_p1;

assign TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_1_address0 = j_5_cast30_fu_431_p1;

assign TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_2_address0 = j_5_cast30_fu_431_p1;

assign TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_3_address0 = j_5_cast30_fu_431_p1;

assign TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_4_address0 = j_5_cast30_fu_431_p1;

assign TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_5_address0 = j_5_cast30_fu_431_p1;

assign TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_6_address0 = j_5_cast30_fu_431_p1;

assign TRANSFORMER_ENCODER_LAYERS_0_SELF_ATTN_O_PROJ_WEIGHT_7_address0 = j_5_cast30_fu_431_p1;

assign add_ln143_1_fu_389_p2 = (ap_sig_allocacmp_i_2 + 4'd1);

assign add_ln143_fu_366_p2 = (ap_sig_allocacmp_indvar_flatten65_load + 7'd1);

assign add_ln145_fu_526_p2 = (select_ln143_reg_576 + 4'd1);

assign add_ln152_fu_471_p2 = (j_5_cast_fu_468_p1 + select_ln143_1_reg_587);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage3_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage2_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage3_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage2_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage3_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage2_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage3_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage1_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage2_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage3_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage1_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage2_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage3_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage1_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage2_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage3_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp0_stage1_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp0_stage2_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp0_stage3_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp0_stage1_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp0_stage2_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state56_pp0_stage3_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state57_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign attn_residual_address0 = zext_ln46_reg_713_pp0_iter13_reg;

assign attn_residual_d0 = add1_reg_873;

assign empty_32_fu_395_p1 = add_ln143_1_fu_389_p2[2:0];

assign empty_fu_348_p1 = ap_sig_allocacmp_i_2[2:0];

assign front_address0 = zext_ln46_fu_476_p1;

assign grp_fu_2070_p_ce = 1'b1;

assign grp_fu_2070_p_din0 = grp_fu_306_p0;

assign grp_fu_2070_p_din1 = grp_fu_306_p1;

assign grp_fu_2070_p_opcode = 2'd0;

assign grp_fu_2074_p_ce = 1'b1;

assign grp_fu_2074_p_din0 = grp_fu_311_p0;

assign grp_fu_2074_p_din1 = grp_fu_311_p1;

assign grp_fu_2074_p_opcode = 2'd0;

assign grp_fu_2078_p_ce = 1'b1;

assign grp_fu_2078_p_din0 = grp_fu_319_p0;

assign grp_fu_2078_p_din1 = grp_fu_319_p1;

assign grp_fu_2082_p_ce = 1'b1;

assign grp_fu_2082_p_din0 = grp_fu_315_p0;

assign grp_fu_2082_p_din1 = grp_fu_315_p1;

assign grp_fu_2082_p_opcode = 2'd0;

assign grp_fu_2146_p_ce = 1'b1;

assign grp_fu_2146_p_din0 = grp_fu_323_p0;

assign grp_fu_2146_p_din1 = grp_fu_323_p1;

assign icmp_ln143_fu_360_p2 = ((ap_sig_allocacmp_indvar_flatten65_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln145_fu_375_p2 = ((ap_sig_allocacmp_j_load == 4'd8) ? 1'b1 : 1'b0);

assign j_5_cast30_fu_431_p1 = select_ln143_fu_381_p3;

assign j_5_cast_fu_468_p1 = select_ln143_reg_576;

assign or_ln143_1_fu_448_p2 = (select_ln143_1_reg_587 | 6'd2);

assign or_ln143_2_fu_458_p2 = (select_ln143_1_reg_587 | 6'd3);

assign or_ln143_3_fu_481_p2 = (select_ln143_1_reg_587 | 6'd4);

assign or_ln143_4_fu_491_p2 = (select_ln143_1_reg_587 | 6'd5);

assign or_ln143_5_fu_501_p2 = (select_ln143_1_reg_587 | 6'd6);

assign or_ln143_6_fu_511_p2 = (select_ln143_1_reg_587 | 6'd7);

assign or_ln143_fu_420_p2 = (select_ln143_1_fu_407_p3 | 6'd1);

assign p_mid4_fu_399_p3 = {{empty_32_fu_395_p1}, {3'd0}};

assign select_ln143_1_fu_407_p3 = ((icmp_ln145_fu_375_p2[0:0] == 1'b1) ? p_mid4_fu_399_p3 : tmp_s_fu_352_p3);

assign select_ln143_2_fu_521_p3 = ((icmp_ln145_reg_571[0:0] == 1'b1) ? add_ln143_1_reg_582 : i_2_reg_562);

assign select_ln143_fu_381_p3 = ((icmp_ln145_fu_375_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_j_load);

assign tmp_s_fu_352_p3 = {{empty_fu_348_p1}, {3'd0}};

assign zext_ln143_1_fu_426_p1 = or_ln143_fu_420_p2;

assign zext_ln143_2_fu_453_p1 = or_ln143_1_fu_448_p2;

assign zext_ln143_3_fu_463_p1 = or_ln143_2_fu_458_p2;

assign zext_ln143_4_fu_486_p1 = or_ln143_3_fu_481_p2;

assign zext_ln143_5_fu_496_p1 = or_ln143_4_fu_491_p2;

assign zext_ln143_6_fu_506_p1 = or_ln143_5_fu_501_p2;

assign zext_ln143_7_fu_516_p1 = or_ln143_6_fu_511_p2;

assign zext_ln143_fu_415_p1 = select_ln143_1_fu_407_p3;

assign zext_ln46_fu_476_p1 = add_ln152_fu_471_p2;

always @ (posedge ap_clk) begin
    select_ln143_1_reg_587[2:0] <= 3'b000;
    j_5_cast30_reg_608[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_5_cast30_reg_608_pp0_iter1_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_5_cast30_reg_608_pp0_iter2_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_5_cast30_reg_608_pp0_iter3_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_5_cast30_reg_608_pp0_iter4_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_5_cast30_reg_608_pp0_iter5_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_5_cast30_reg_608_pp0_iter6_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_5_cast30_reg_608_pp0_iter7_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_5_cast30_reg_608_pp0_iter8_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_5_cast30_reg_608_pp0_iter9_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_5_cast30_reg_608_pp0_iter10_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713_pp0_iter3_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713_pp0_iter4_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713_pp0_iter5_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713_pp0_iter6_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713_pp0_iter7_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713_pp0_iter8_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713_pp0_iter9_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713_pp0_iter10_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713_pp0_iter11_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713_pp0_iter12_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln46_reg_713_pp0_iter13_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j
