// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module transformer_transformer_for_sample_Pipeline_front_linear_i_front_linear_j (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        input_array,
        front_address0,
        front_ce0,
        front_we0,
        front_d0,
        grp_fu_2070_p_din0,
        grp_fu_2070_p_din1,
        grp_fu_2070_p_opcode,
        grp_fu_2070_p_dout0,
        grp_fu_2070_p_ce,
        grp_fu_2074_p_din0,
        grp_fu_2074_p_din1,
        grp_fu_2074_p_opcode,
        grp_fu_2074_p_dout0,
        grp_fu_2074_p_ce,
        grp_fu_2078_p_din0,
        grp_fu_2078_p_din1,
        grp_fu_2078_p_dout0,
        grp_fu_2078_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [31:0] m_axi_gmem0_WDATA;
output  [3:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [31:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [63:0] input_array;
output  [5:0] front_address0;
output   front_ce0;
output   front_we0;
output  [31:0] front_d0;
output  [31:0] grp_fu_2070_p_din0;
output  [31:0] grp_fu_2070_p_din1;
output  [1:0] grp_fu_2070_p_opcode;
input  [31:0] grp_fu_2070_p_dout0;
output   grp_fu_2070_p_ce;
output  [31:0] grp_fu_2074_p_din0;
output  [31:0] grp_fu_2074_p_din1;
output  [1:0] grp_fu_2074_p_opcode;
input  [31:0] grp_fu_2074_p_dout0;
output   grp_fu_2074_p_ce;
output  [31:0] grp_fu_2078_p_din0;
output  [31:0] grp_fu_2078_p_din1;
input  [31:0] grp_fu_2078_p_dout0;
output   grp_fu_2078_p_ce;

reg ap_idle;
reg m_axi_gmem0_ARVALID;
reg[63:0] m_axi_gmem0_ARADDR;
reg m_axi_gmem0_RREADY;
reg front_ce0;
reg front_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
reg   [0:0] icmp_ln54_reg_410;
reg    ap_block_state2_io;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_state8_pp0_stage1_iter3;
reg    ap_block_state10_pp0_stage1_iter4;
wire    ap_block_state12_pp0_stage1_iter5;
wire    ap_block_state14_pp0_stage1_iter6;
wire    ap_block_state16_pp0_stage1_iter7;
wire    ap_block_state18_pp0_stage1_iter8;
wire    ap_block_state20_pp0_stage1_iter9;
wire    ap_block_state22_pp0_stage1_iter10;
wire    ap_block_state24_pp0_stage1_iter11;
wire    ap_block_state26_pp0_stage1_iter12;
wire    ap_block_state28_pp0_stage1_iter13;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] FRONT_LINEAR_WEIGHT_0_address0;
reg    FRONT_LINEAR_WEIGHT_0_ce0;
wire   [31:0] FRONT_LINEAR_WEIGHT_0_q0;
wire   [2:0] FRONT_LINEAR_WEIGHT_1_address0;
reg    FRONT_LINEAR_WEIGHT_1_ce0;
wire   [31:0] FRONT_LINEAR_WEIGHT_1_q0;
wire   [2:0] FRONT_LINEAR_BIAS_address0;
reg    FRONT_LINEAR_BIAS_ce0;
wire   [31:0] FRONT_LINEAR_BIAS_q0;
reg    gmem0_blk_n_AR;
wire    ap_block_pp0_stage1;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
reg    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_state11_pp0_stage0_iter5;
wire    ap_block_state13_pp0_stage0_iter6;
wire    ap_block_state15_pp0_stage0_iter7;
wire    ap_block_state17_pp0_stage0_iter8;
wire    ap_block_state19_pp0_stage0_iter9;
wire    ap_block_state21_pp0_stage0_iter10;
wire    ap_block_state23_pp0_stage0_iter11;
wire    ap_block_state25_pp0_stage0_iter12;
wire    ap_block_state27_pp0_stage0_iter13;
wire    ap_block_state29_pp0_stage0_iter14;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln54_fu_205_p2;
reg   [0:0] icmp_ln54_reg_410_pp0_iter1_reg;
reg   [0:0] icmp_ln54_reg_410_pp0_iter2_reg;
reg   [0:0] icmp_ln54_reg_410_pp0_iter3_reg;
reg   [0:0] icmp_ln54_reg_410_pp0_iter4_reg;
reg   [0:0] icmp_ln54_reg_410_pp0_iter5_reg;
reg   [0:0] icmp_ln54_reg_410_pp0_iter6_reg;
reg   [0:0] icmp_ln54_reg_410_pp0_iter7_reg;
reg   [0:0] icmp_ln54_reg_410_pp0_iter8_reg;
reg   [0:0] icmp_ln54_reg_410_pp0_iter9_reg;
reg   [0:0] icmp_ln54_reg_410_pp0_iter10_reg;
reg   [0:0] icmp_ln54_reg_410_pp0_iter11_reg;
reg   [0:0] icmp_ln54_reg_410_pp0_iter12_reg;
reg   [3:0] j_load_reg_414;
wire   [0:0] icmp_ln56_fu_223_p2;
reg   [0:0] icmp_ln56_reg_419;
wire   [3:0] select_ln54_1_fu_235_p3;
reg   [3:0] select_ln54_1_reg_424;
wire   [5:0] p_mid2_fu_247_p3;
reg   [5:0] p_mid2_reg_429;
reg   [5:0] p_mid2_reg_429_pp0_iter1_reg;
reg   [5:0] p_mid2_reg_429_pp0_iter2_reg;
reg   [5:0] p_mid2_reg_429_pp0_iter3_reg;
reg   [5:0] p_mid2_reg_429_pp0_iter4_reg;
reg   [63:0] gmem0_addr_reg_434;
wire   [3:0] select_ln54_fu_295_p3;
reg   [3:0] select_ln54_reg_440;
reg    ap_block_pp0_stage1_11001;
reg   [3:0] select_ln54_reg_440_pp0_iter1_reg;
reg   [3:0] select_ln54_reg_440_pp0_iter2_reg;
reg   [3:0] select_ln54_reg_440_pp0_iter3_reg;
reg   [3:0] select_ln54_reg_440_pp0_iter4_reg;
reg   [63:0] gmem0_addr_1_reg_446;
wire   [63:0] j_cast20_fu_360_p1;
reg   [63:0] j_cast20_reg_452;
reg   [63:0] j_cast20_reg_452_pp0_iter4_reg;
reg   [63:0] j_cast20_reg_452_pp0_iter5_reg;
reg   [63:0] j_cast20_reg_452_pp0_iter6_reg;
reg   [63:0] j_cast20_reg_452_pp0_iter7_reg;
reg   [63:0] j_cast20_reg_452_pp0_iter8_reg;
reg   [63:0] j_cast20_reg_452_pp0_iter9_reg;
reg   [31:0] FRONT_LINEAR_WEIGHT_0_load_reg_463;
reg   [31:0] gmem0_addr_read_reg_468;
wire   [31:0] bitcast_ln60_fu_364_p1;
reg   [31:0] gmem0_addr_1_read_reg_483;
reg   [31:0] FRONT_LINEAR_WEIGHT_1_load_reg_488;
wire   [31:0] bitcast_ln60_1_fu_371_p1;
wire   [5:0] add_ln62_fu_375_p2;
reg   [5:0] add_ln62_reg_498;
reg   [5:0] add_ln62_reg_498_pp0_iter6_reg;
reg   [5:0] add_ln62_reg_498_pp0_iter7_reg;
reg   [5:0] add_ln62_reg_498_pp0_iter8_reg;
reg   [5:0] add_ln62_reg_498_pp0_iter9_reg;
reg   [5:0] add_ln62_reg_498_pp0_iter10_reg;
reg   [5:0] add_ln62_reg_498_pp0_iter11_reg;
reg   [5:0] add_ln62_reg_498_pp0_iter12_reg;
reg   [5:0] add_ln62_reg_498_pp0_iter13_reg;
reg   [31:0] mul_reg_503;
reg   [31:0] mul_1_reg_508;
reg   [31:0] mul_1_reg_508_pp0_iter7_reg;
reg   [31:0] mul_1_reg_508_pp0_iter8_reg;
reg   [31:0] sum_1_reg_513;
reg   [31:0] FRONT_LINEAR_BIAS_load_reg_523;
reg   [31:0] sum_1_1_reg_528;
reg   [31:0] add_reg_533;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln62_fu_380_p1;
wire  signed [63:0] sext_ln54_fu_275_p1;
wire  signed [63:0] sext_ln54_1_fu_339_p1;
reg   [3:0] j_fu_80;
wire   [3:0] add_ln56_fu_349_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_load;
reg   [3:0] i_fu_84;
reg   [3:0] ap_sig_allocacmp_i_load;
reg   [6:0] indvar_flatten_fu_88;
wire   [6:0] add_ln54_fu_211_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [31:0] grp_fu_174_p0;
reg   [31:0] grp_fu_174_p1;
reg   [31:0] grp_fu_183_p0;
reg   [31:0] grp_fu_183_p1;
wire   [3:0] add_ln54_3_fu_229_p2;
wire   [2:0] trunc_ln54_fu_243_p1;
wire   [63:0] zext_ln54_fu_255_p1;
wire   [63:0] add_ln54_1_fu_259_p2;
wire   [61:0] sext_ln60_mid2_v_fu_265_p4;
wire   [3:0] shl_ln54_fu_301_p2;
wire   [3:0] or_ln54_fu_306_p2;
wire   [5:0] sext_ln60_1_mid2_v_v_v_v_v_fu_312_p3;
wire   [63:0] zext_ln54_1_fu_320_p1;
wire   [63:0] add_ln54_2_fu_324_p2;
wire   [61:0] sext_ln60_1_mid2_v_fu_329_p4;
wire   [5:0] j_cast_fu_368_p1;
reg    grp_fu_174_ce;
reg    grp_fu_179_ce;
reg    grp_fu_183_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter13_stage0;
reg    ap_idle_pp0_0to12;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to14;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_block_pp0_stage1_00001;
reg    ap_block_pp0_stage0_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

transformer_transformer_for_sample_Pipeline_front_linear_i_front_linear_j_FRONT_LINEAR_WEbkb #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
FRONT_LINEAR_WEIGHT_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FRONT_LINEAR_WEIGHT_0_address0),
    .ce0(FRONT_LINEAR_WEIGHT_0_ce0),
    .q0(FRONT_LINEAR_WEIGHT_0_q0)
);

transformer_transformer_for_sample_Pipeline_front_linear_i_front_linear_j_FRONT_LINEAR_WEcud #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
FRONT_LINEAR_WEIGHT_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FRONT_LINEAR_WEIGHT_1_address0),
    .ce0(FRONT_LINEAR_WEIGHT_1_ce0),
    .q0(FRONT_LINEAR_WEIGHT_1_q0)
);

transformer_transformer_for_sample_Pipeline_front_linear_i_front_linear_j_FRONT_LINEAR_BIdEe #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
FRONT_LINEAR_BIAS_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FRONT_LINEAR_BIAS_address0),
    .ce0(FRONT_LINEAR_BIAS_ce0),
    .q0(FRONT_LINEAR_BIAS_q0)
);

transformer_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter14 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln54_fu_205_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_84 <= select_ln54_1_fu_235_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_84 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln54_fu_205_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_88 <= add_ln54_fu_211_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_88 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_fu_80 <= 4'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln54_reg_410 == 1'd0))) begin
        j_fu_80 <= add_ln56_fu_349_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        FRONT_LINEAR_BIAS_load_reg_523 <= FRONT_LINEAR_BIAS_q0;
        FRONT_LINEAR_WEIGHT_0_load_reg_463 <= FRONT_LINEAR_WEIGHT_0_q0;
        FRONT_LINEAR_WEIGHT_1_load_reg_488 <= FRONT_LINEAR_WEIGHT_1_q0;
        add_reg_533 <= grp_fu_2074_p_dout0;
        gmem0_addr_1_read_reg_483 <= m_axi_gmem0_RDATA;
        mul_1_reg_508_pp0_iter7_reg <= mul_1_reg_508;
        mul_1_reg_508_pp0_iter8_reg <= mul_1_reg_508_pp0_iter7_reg;
        select_ln54_reg_440_pp0_iter1_reg <= select_ln54_reg_440;
        select_ln54_reg_440_pp0_iter2_reg <= select_ln54_reg_440_pp0_iter1_reg;
        select_ln54_reg_440_pp0_iter3_reg <= select_ln54_reg_440_pp0_iter2_reg;
        select_ln54_reg_440_pp0_iter4_reg <= select_ln54_reg_440_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln62_reg_498 <= add_ln62_fu_375_p2;
        add_ln62_reg_498_pp0_iter10_reg <= add_ln62_reg_498_pp0_iter9_reg;
        add_ln62_reg_498_pp0_iter11_reg <= add_ln62_reg_498_pp0_iter10_reg;
        add_ln62_reg_498_pp0_iter12_reg <= add_ln62_reg_498_pp0_iter11_reg;
        add_ln62_reg_498_pp0_iter13_reg <= add_ln62_reg_498_pp0_iter12_reg;
        add_ln62_reg_498_pp0_iter6_reg <= add_ln62_reg_498;
        add_ln62_reg_498_pp0_iter7_reg <= add_ln62_reg_498_pp0_iter6_reg;
        add_ln62_reg_498_pp0_iter8_reg <= add_ln62_reg_498_pp0_iter7_reg;
        add_ln62_reg_498_pp0_iter9_reg <= add_ln62_reg_498_pp0_iter8_reg;
        gmem0_addr_read_reg_468 <= m_axi_gmem0_RDATA;
        icmp_ln54_reg_410 <= icmp_ln54_fu_205_p2;
        icmp_ln54_reg_410_pp0_iter10_reg <= icmp_ln54_reg_410_pp0_iter9_reg;
        icmp_ln54_reg_410_pp0_iter11_reg <= icmp_ln54_reg_410_pp0_iter10_reg;
        icmp_ln54_reg_410_pp0_iter12_reg <= icmp_ln54_reg_410_pp0_iter11_reg;
        icmp_ln54_reg_410_pp0_iter1_reg <= icmp_ln54_reg_410;
        icmp_ln54_reg_410_pp0_iter2_reg <= icmp_ln54_reg_410_pp0_iter1_reg;
        icmp_ln54_reg_410_pp0_iter3_reg <= icmp_ln54_reg_410_pp0_iter2_reg;
        icmp_ln54_reg_410_pp0_iter4_reg <= icmp_ln54_reg_410_pp0_iter3_reg;
        icmp_ln54_reg_410_pp0_iter5_reg <= icmp_ln54_reg_410_pp0_iter4_reg;
        icmp_ln54_reg_410_pp0_iter6_reg <= icmp_ln54_reg_410_pp0_iter5_reg;
        icmp_ln54_reg_410_pp0_iter7_reg <= icmp_ln54_reg_410_pp0_iter6_reg;
        icmp_ln54_reg_410_pp0_iter8_reg <= icmp_ln54_reg_410_pp0_iter7_reg;
        icmp_ln54_reg_410_pp0_iter9_reg <= icmp_ln54_reg_410_pp0_iter8_reg;
        j_cast20_reg_452[3 : 0] <= j_cast20_fu_360_p1[3 : 0];
        j_cast20_reg_452_pp0_iter4_reg[3 : 0] <= j_cast20_reg_452[3 : 0];
        j_cast20_reg_452_pp0_iter5_reg[3 : 0] <= j_cast20_reg_452_pp0_iter4_reg[3 : 0];
        j_cast20_reg_452_pp0_iter6_reg[3 : 0] <= j_cast20_reg_452_pp0_iter5_reg[3 : 0];
        j_cast20_reg_452_pp0_iter7_reg[3 : 0] <= j_cast20_reg_452_pp0_iter6_reg[3 : 0];
        j_cast20_reg_452_pp0_iter8_reg[3 : 0] <= j_cast20_reg_452_pp0_iter7_reg[3 : 0];
        j_cast20_reg_452_pp0_iter9_reg[3 : 0] <= j_cast20_reg_452_pp0_iter8_reg[3 : 0];
        p_mid2_reg_429_pp0_iter1_reg[5 : 3] <= p_mid2_reg_429[5 : 3];
        p_mid2_reg_429_pp0_iter2_reg[5 : 3] <= p_mid2_reg_429_pp0_iter1_reg[5 : 3];
        p_mid2_reg_429_pp0_iter3_reg[5 : 3] <= p_mid2_reg_429_pp0_iter2_reg[5 : 3];
        p_mid2_reg_429_pp0_iter4_reg[5 : 3] <= p_mid2_reg_429_pp0_iter3_reg[5 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln54_reg_410 == 1'd0))) begin
        gmem0_addr_1_reg_446 <= sext_ln54_1_fu_339_p1;
        select_ln54_reg_440 <= select_ln54_fu_295_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln54_fu_205_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem0_addr_reg_434 <= sext_ln54_fu_275_p1;
        icmp_ln56_reg_419 <= icmp_ln56_fu_223_p2;
        j_load_reg_414 <= ap_sig_allocacmp_j_load;
        p_mid2_reg_429[5 : 3] <= p_mid2_fu_247_p3[5 : 3];
        select_ln54_1_reg_424 <= select_ln54_1_fu_235_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        mul_1_reg_508 <= grp_fu_2078_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_reg_503 <= grp_fu_2078_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_1_1_reg_528 <= grp_fu_2070_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        sum_1_reg_513 <= grp_fu_2070_p_dout0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        FRONT_LINEAR_BIAS_ce0 = 1'b1;
    end else begin
        FRONT_LINEAR_BIAS_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        FRONT_LINEAR_WEIGHT_0_ce0 = 1'b1;
    end else begin
        FRONT_LINEAR_WEIGHT_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        FRONT_LINEAR_WEIGHT_1_ce0 = 1'b1;
    end else begin
        FRONT_LINEAR_WEIGHT_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln54_reg_410 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (icmp_ln54_reg_410_pp0_iter12_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter13_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter13_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to12 = 1'b1;
    end else begin
        ap_idle_pp0_0to12 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to14 = 1'b1;
    end else begin
        ap_idle_pp0_1to14 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_84;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_88;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_80;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        front_ce0 = 1'b1;
    end else begin
        front_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        front_we0 = 1'b1;
    end else begin
        front_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (icmp_ln54_reg_410 == 1'd0)))) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_174_ce = 1'b1;
    end else begin
        grp_fu_174_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_174_p0 = sum_1_reg_513;
    end else if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_174_p0 = mul_reg_503;
    end else begin
        grp_fu_174_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_174_p1 = mul_1_reg_508_pp0_iter8_reg;
    end else if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_174_p1 = 32'd0;
    end else begin
        grp_fu_174_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_179_ce = 1'b1;
    end else begin
        grp_fu_179_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_183_ce = 1'b1;
    end else begin
        grp_fu_183_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_183_p0 = bitcast_ln60_1_fu_371_p1;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_183_p0 = bitcast_ln60_fu_364_p1;
    end else begin
        grp_fu_183_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_183_p1 = FRONT_LINEAR_WEIGHT_1_load_reg_488;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_183_p1 = FRONT_LINEAR_WEIGHT_0_load_reg_463;
    end else begin
        grp_fu_183_p1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem0_ARADDR = gmem0_addr_1_reg_446;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln54_reg_410 == 1'd0))) begin
        m_axi_gmem0_ARADDR = gmem0_addr_reg_434;
    end else begin
        m_axi_gmem0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln54_reg_410 == 1'd0)))) begin
        m_axi_gmem0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to12 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter13_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to14 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign FRONT_LINEAR_BIAS_address0 = j_cast20_reg_452_pp0_iter9_reg;

assign FRONT_LINEAR_WEIGHT_0_address0 = j_cast20_fu_360_p1;

assign FRONT_LINEAR_WEIGHT_1_address0 = j_cast20_reg_452;

assign add_ln54_1_fu_259_p2 = (zext_ln54_fu_255_p1 + input_array);

assign add_ln54_2_fu_324_p2 = (zext_ln54_1_fu_320_p1 + input_array);

assign add_ln54_3_fu_229_p2 = (ap_sig_allocacmp_i_load + 4'd1);

assign add_ln54_fu_211_p2 = (ap_sig_allocacmp_indvar_flatten_load + 7'd1);

assign add_ln56_fu_349_p2 = (select_ln54_fu_295_p3 + 4'd1);

assign add_ln62_fu_375_p2 = (j_cast_fu_368_p1 + p_mid2_reg_429_pp0_iter4_reg);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((m_axi_gmem0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((m_axi_gmem0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_00001 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_state10_pp0_stage1_iter4 = (m_axi_gmem0_RVALID == 1'b0);
end

assign ap_block_state11_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage1_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage1_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage1_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage1_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage1_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_io = ((m_axi_gmem0_ARREADY == 1'b0) & (icmp_ln54_reg_410 == 1'd0));
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter4 = (m_axi_gmem0_RVALID == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign bitcast_ln60_1_fu_371_p1 = gmem0_addr_1_read_reg_483;

assign bitcast_ln60_fu_364_p1 = gmem0_addr_read_reg_468;

assign front_address0 = zext_ln62_fu_380_p1;

assign front_d0 = add_reg_533;

assign grp_fu_2070_p_ce = grp_fu_174_ce;

assign grp_fu_2070_p_din0 = grp_fu_174_p0;

assign grp_fu_2070_p_din1 = grp_fu_174_p1;

assign grp_fu_2070_p_opcode = 2'd0;

assign grp_fu_2074_p_ce = grp_fu_179_ce;

assign grp_fu_2074_p_din0 = sum_1_1_reg_528;

assign grp_fu_2074_p_din1 = FRONT_LINEAR_BIAS_load_reg_523;

assign grp_fu_2074_p_opcode = 2'd0;

assign grp_fu_2078_p_ce = grp_fu_183_ce;

assign grp_fu_2078_p_din0 = grp_fu_183_p0;

assign grp_fu_2078_p_din1 = grp_fu_183_p1;

assign icmp_ln54_fu_205_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_223_p2 = ((ap_sig_allocacmp_j_load == 4'd8) ? 1'b1 : 1'b0);

assign j_cast20_fu_360_p1 = select_ln54_reg_440_pp0_iter2_reg;

assign j_cast_fu_368_p1 = select_ln54_reg_440_pp0_iter4_reg;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 32'd1;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 32'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 4'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign or_ln54_fu_306_p2 = (shl_ln54_fu_301_p2 | 4'd1);

assign p_mid2_fu_247_p3 = {{trunc_ln54_fu_243_p1}, {3'd0}};

assign select_ln54_1_fu_235_p3 = ((icmp_ln56_fu_223_p2[0:0] == 1'b1) ? add_ln54_3_fu_229_p2 : ap_sig_allocacmp_i_load);

assign select_ln54_fu_295_p3 = ((icmp_ln56_reg_419[0:0] == 1'b1) ? 4'd0 : j_load_reg_414);

assign sext_ln54_1_fu_339_p1 = $signed(sext_ln60_1_mid2_v_fu_329_p4);

assign sext_ln54_fu_275_p1 = $signed(sext_ln60_mid2_v_fu_265_p4);

assign sext_ln60_1_mid2_v_fu_329_p4 = {{add_ln54_2_fu_324_p2[63:2]}};

assign sext_ln60_1_mid2_v_v_v_v_v_fu_312_p3 = {{or_ln54_fu_306_p2}, {2'd0}};

assign sext_ln60_mid2_v_fu_265_p4 = {{add_ln54_1_fu_259_p2[63:2]}};

assign shl_ln54_fu_301_p2 = select_ln54_1_reg_424 << 4'd1;

assign trunc_ln54_fu_243_p1 = select_ln54_1_fu_235_p3[2:0];

assign zext_ln54_1_fu_320_p1 = sext_ln60_1_mid2_v_v_v_v_v_fu_312_p3;

assign zext_ln54_fu_255_p1 = p_mid2_fu_247_p3;

assign zext_ln62_fu_380_p1 = add_ln62_reg_498_pp0_iter13_reg;

always @ (posedge ap_clk) begin
    p_mid2_reg_429[2:0] <= 3'b000;
    p_mid2_reg_429_pp0_iter1_reg[2:0] <= 3'b000;
    p_mid2_reg_429_pp0_iter2_reg[2:0] <= 3'b000;
    p_mid2_reg_429_pp0_iter3_reg[2:0] <= 3'b000;
    p_mid2_reg_429_pp0_iter4_reg[2:0] <= 3'b000;
    j_cast20_reg_452[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_cast20_reg_452_pp0_iter4_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_cast20_reg_452_pp0_iter5_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_cast20_reg_452_pp0_iter6_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_cast20_reg_452_pp0_iter7_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_cast20_reg_452_pp0_iter8_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    j_cast20_reg_452_pp0_iter9_reg[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //transformer_transformer_for_sample_Pipeline_front_linear_i_front_linear_j
