-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity unsw_linear_transformer_unsw_linear_transformer_Pipeline_VITIS_LOOP_199_21 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln837_9 : IN STD_LOGIC_VECTOR (6 downto 0);
    query_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    query_V_ce0 : OUT STD_LOGIC;
    query_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    key_sum_arr_V_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    key_sum_arr_V_ce0 : OUT STD_LOGIC;
    key_sum_arr_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    denominator_V_5_out : OUT STD_LOGIC_VECTOR (27 downto 0);
    denominator_V_5_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of unsw_linear_transformer_unsw_linear_transformer_Pipeline_VITIS_LOOP_199_21 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv28_0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv28_7FFFFFF : STD_LOGIC_VECTOR (27 downto 0) := "0111111111111111111111111111";
    constant ap_const_lv28_8000000 : STD_LOGIC_VECTOR (27 downto 0) := "1000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal icmp_ln199_reg_429 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln199_fu_132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal query_V_load_reg_443 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal key_sum_arr_V_load_reg_448 : STD_LOGIC_VECTOR (15 downto 0);
    signal r_V_12_fu_191_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal r_V_12_reg_453 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_reg_459 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_fu_223_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal ret_V_reg_464 : STD_LOGIC_VECTOR (44 downto 0);
    signal p_Result_s_reg_469 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_29_reg_475 : STD_LOGIC_VECTOR (0 downto 0);
    signal denominator_V_2_fu_263_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal denominator_V_2_reg_481 : STD_LOGIC_VECTOR (27 downto 0);
    signal p_Result_30_reg_486 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_reg_493 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln837_12_fu_159_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln199_fu_144_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lhs_fu_72 : STD_LOGIC_VECTOR (27 downto 0);
    signal denominator_V_fu_398_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal feature_1_fu_76 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln199_fu_138_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_feature : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln837_fu_149_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln837_fu_153_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal r_V_fu_169_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal shl_ln838_8_fu_176_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal lhs_4_fu_208_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal sext_ln1347_fu_216_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal sext_ln1347_10_fu_220_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal add_ln1347_7_fu_229_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal zext_ln377_fu_260_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal denominator_V_1_fu_242_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal xor_ln896_14_fu_285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln888_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln888_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_310_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln890_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln890_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_12_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln895_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln895_12_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln896_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln891_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln896_fu_367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln896_19_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_379_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln346_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_fu_384_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to2 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component unsw_linear_transformer_mul_22s_22s_44_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (21 downto 0);
        din1 : IN STD_LOGIC_VECTOR (21 downto 0);
        dout : OUT STD_LOGIC_VECTOR (43 downto 0) );
    end component;


    component unsw_linear_transformer_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_22s_22s_44_1_1_U42 : component unsw_linear_transformer_mul_22s_22s_44_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 22,
        din1_WIDTH => 22,
        dout_WIDTH => 44)
    port map (
        din0 => shl_ln838_8_fu_176_p3,
        din1 => r_V_fu_169_p3,
        dout => r_V_12_fu_191_p2);

    flow_control_loop_pipe_sequential_init_U : component unsw_linear_transformer_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    feature_1_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln199_fu_132_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    feature_1_fu_76 <= add_ln199_fu_138_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    feature_1_fu_76 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    lhs_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    lhs_fu_72 <= ap_const_lv28_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    lhs_fu_72 <= denominator_V_fu_398_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                Range2_all_ones_reg_493 <= ret_V_fu_223_p2(44 downto 44);
                denominator_V_2_reg_481 <= denominator_V_2_fu_263_p2;
                p_Result_29_reg_475 <= add_ln1347_7_fu_229_p2(43 downto 43);
                p_Result_30_reg_486 <= denominator_V_2_fu_263_p2(27 downto 27);
                p_Result_s_reg_469 <= ret_V_fu_223_p2(44 downto 44);
                ret_V_reg_464 <= ret_V_fu_223_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln199_reg_429 <= icmp_ln199_fu_132_p2;
                r_V_12_reg_453 <= r_V_12_fu_191_p2;
                tmp_reg_459 <= r_V_12_fu_191_p2(15 downto 15);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln199_reg_429 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                key_sum_arr_V_load_reg_448 <= key_sum_arr_V_q0;
                query_V_load_reg_443 <= query_V_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter1_stage0, ap_idle_pp0_0to0, ap_idle_pp0_1to2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to2 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln1347_7_fu_229_p2 <= std_logic_vector(signed(lhs_4_fu_208_p3) + signed(r_V_12_reg_453));
    add_ln199_fu_138_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_feature) + unsigned(ap_const_lv5_1));
    add_ln837_fu_153_p2 <= std_logic_vector(unsigned(zext_ln837_9) + unsigned(zext_ln837_fu_149_p1));
    and_ln891_fu_334_p2 <= (carry_12_fu_290_p2 and Range2_all_ones_reg_493);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, icmp_ln199_reg_429)
    begin
        if (((icmp_ln199_reg_429 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln199_reg_429, ap_block_pp0_stage0_subdone)
    begin
        if (((icmp_ln199_reg_429 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_feature_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, feature_1_fu_76)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_feature <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_feature <= feature_1_fu_76;
        end if; 
    end process;

    carry_12_fu_290_p2 <= (xor_ln896_14_fu_285_p2 and p_Result_29_reg_475);
    deleted_ones_fu_329_p2 <= (or_ln890_fu_323_p2 and Range2_all_ones_reg_493);
    deleted_zeros_fu_305_p2 <= (or_ln888_fu_300_p2 xor Range2_all_ones_reg_493);
    denominator_V_1_fu_242_p4 <= add_ln1347_7_fu_229_p2(43 downto 16);
    denominator_V_2_fu_263_p2 <= std_logic_vector(unsigned(zext_ln377_fu_260_p1) + unsigned(denominator_V_1_fu_242_p4));
    denominator_V_5_out <= lhs_fu_72;

    denominator_V_5_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln199_reg_429, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln199_reg_429 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            denominator_V_5_out_ap_vld <= ap_const_logic_1;
        else 
            denominator_V_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    denominator_V_fu_398_p3 <= 
        select_ln346_fu_384_p3 when (or_ln346_fu_392_p2(0) = '1') else 
        denominator_V_2_reg_481;
    icmp_ln199_fu_132_p2 <= "1" when (ap_sig_allocacmp_feature = ap_const_lv5_10) else "0";
    key_sum_arr_V_address0 <= zext_ln199_fu_144_p1(4 - 1 downto 0);

    key_sum_arr_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            key_sum_arr_V_ce0 <= ap_const_logic_1;
        else 
            key_sum_arr_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    lhs_4_fu_208_p3 <= (lhs_fu_72 & ap_const_lv16_0);
    or_ln346_fu_392_p2 <= (underflow_fu_379_p2 or overflow_fu_355_p2);
    or_ln888_fu_300_p2 <= (xor_ln888_fu_295_p2 or p_Result_30_reg_486);
    or_ln890_fu_323_p2 <= (xor_ln890_fu_317_p2 or or_ln888_fu_300_p2);
    or_ln895_fu_345_p2 <= (xor_ln895_fu_339_p2 or p_Result_30_reg_486);
    or_ln896_fu_367_p2 <= (xor_ln896_fu_361_p2 or xor_ln896_14_fu_285_p2);
    overflow_fu_355_p2 <= (xor_ln895_12_fu_350_p2 and or_ln895_fu_345_p2);
    query_V_address0 <= zext_ln837_12_fu_159_p1(7 - 1 downto 0);

    query_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            query_V_ce0 <= ap_const_logic_1;
        else 
            query_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    r_V_fu_169_p3 <= (query_V_load_reg_443 & ap_const_lv6_0);
    ret_V_fu_223_p2 <= std_logic_vector(signed(sext_ln1347_fu_216_p1) + signed(sext_ln1347_10_fu_220_p1));
    select_ln346_fu_384_p3 <= 
        ap_const_lv28_7FFFFFF when (overflow_fu_355_p2(0) = '1') else 
        ap_const_lv28_8000000;
        sext_ln1347_10_fu_220_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_12_reg_453),45));

        sext_ln1347_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(lhs_4_fu_208_p3),45));

    shl_ln838_8_fu_176_p3 <= (key_sum_arr_V_load_reg_448 & ap_const_lv6_0);
    tmp_40_fu_310_p3 <= ret_V_reg_464(44 downto 44);
    underflow_fu_379_p2 <= (xor_ln896_19_fu_373_p2 and p_Result_s_reg_469);
    xor_ln888_fu_295_p2 <= (p_Result_29_reg_475 xor ap_const_lv1_1);
    xor_ln890_fu_317_p2 <= (tmp_40_fu_310_p3 xor ap_const_lv1_1);
    xor_ln895_12_fu_350_p2 <= (p_Result_s_reg_469 xor ap_const_lv1_1);
    xor_ln895_fu_339_p2 <= (deleted_zeros_fu_305_p2 xor ap_const_lv1_1);
    xor_ln896_14_fu_285_p2 <= (p_Result_30_reg_486 xor ap_const_lv1_1);
    xor_ln896_19_fu_373_p2 <= (or_ln896_fu_367_p2 xor and_ln891_fu_334_p2);
    xor_ln896_fu_361_p2 <= (deleted_ones_fu_329_p2 xor ap_const_lv1_1);
    zext_ln199_fu_144_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_feature),64));
    zext_ln377_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_459),28));
    zext_ln837_12_fu_159_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln837_fu_153_p2),64));
    zext_ln837_fu_149_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_feature),7));
end behav;
