#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed May 20 15:26:30 CST 2026
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim transformer_design_wrapper_behav -key {Behavioral:sim_1:Functional:transformer_design_wrapper} -tclbatch transformer_design_wrapper.tcl -protoinst "protoinst_files/transformer_design.protoinst" -log simulate.log"
xsim transformer_design_wrapper_behav -key {Behavioral:sim_1:Functional:transformer_design_wrapper} -tclbatch transformer_design_wrapper.tcl -protoinst "protoinst_files/transformer_design.protoinst" -log simulate.log

