// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module unsw_linear_transformer_unsw_linear_transformer_Pipeline_VITIS_LOOP_140_11 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln837_6,
        zext_ln142,
        embedded_V_address0,
        embedded_V_ce0,
        embedded_V_q0,
        key_sum_V_4_out,
        key_sum_V_4_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] zext_ln837_6;
input  [6:0] zext_ln142;
output  [6:0] embedded_V_address0;
output   embedded_V_ce0;
input  [15:0] embedded_V_q0;
output  [23:0] key_sum_V_4_out;
output   key_sum_V_4_out_ap_vld;

reg ap_idle;
reg embedded_V_ce0;
reg key_sum_V_4_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln140_fu_144_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] LAYERS_0_ATTENTION_KEY_WEIGHT_V_address0;
reg    LAYERS_0_ATTENTION_KEY_WEIGHT_V_ce0;
wire   [10:0] LAYERS_0_ATTENTION_KEY_WEIGHT_V_q0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln140_reg_469;
reg   [0:0] icmp_ln140_reg_469_pp0_iter1_reg;
reg   [0:0] icmp_ln140_reg_469_pp0_iter2_reg;
reg   [0:0] icmp_ln140_reg_469_pp0_iter3_reg;
wire  signed [34:0] grp_fu_447_p2;
reg  signed [34:0] r_V_reg_493;
reg   [0:0] tmp_reg_499;
wire   [63:0] zext_ln837_17_fu_170_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln142_1_fu_181_p1;
reg   [23:0] lhs_fu_78;
wire   [23:0] key_sum_V_fu_430_p3;
wire    ap_loop_init;
reg   [4:0] input_feature_2_fu_82;
wire   [4:0] add_ln140_fu_150_p2;
reg   [4:0] ap_sig_allocacmp_input_feature;
wire    ap_block_pp0_stage0_01001;
wire   [7:0] zext_ln837_16_fu_160_p1;
wire   [7:0] add_ln837_4_fu_164_p2;
wire   [6:0] zext_ln837_fu_156_p1;
wire   [6:0] add_ln142_fu_175_p2;
wire  signed [19:0] r_V_7_fu_191_p3;
wire  signed [14:0] shl_ln838_5_fu_199_p3;
wire  signed [37:0] lhs_5_fu_225_p3;
wire  signed [38:0] sext_ln1347_6_fu_233_p1;
wire  signed [38:0] sext_ln1347_7_fu_237_p1;
wire  signed [37:0] sext_ln1347_8_fu_240_p1;
wire   [38:0] ret_V_fu_243_p2;
wire   [37:0] add_ln1347_9_fu_249_p2;
wire   [23:0] zext_ln377_fu_281_p1;
wire   [23:0] key_sum_V_3_fu_263_p4;
wire   [23:0] key_sum_V_4_fu_284_p2;
wire   [0:0] p_Result_37_fu_290_p3;
wire   [0:0] p_Result_36_fu_273_p3;
wire   [0:0] xor_ln896_5_fu_298_p2;
wire   [0:0] xor_ln888_4_fu_318_p2;
wire   [0:0] Range2_all_ones_fu_310_p3;
wire   [0:0] or_ln888_fu_324_p2;
wire   [0:0] tmp_49_fu_336_p3;
wire   [0:0] xor_ln890_fu_344_p2;
wire   [0:0] or_ln890_fu_350_p2;
wire   [0:0] carry_15_fu_304_p2;
wire   [0:0] deleted_zeros_fu_330_p2;
wire   [0:0] xor_ln895_10_fu_368_p2;
wire   [0:0] p_Result_s_fu_255_p3;
wire   [0:0] or_ln895_fu_374_p2;
wire   [0:0] xor_ln895_11_fu_380_p2;
wire   [0:0] deleted_ones_fu_356_p2;
wire   [0:0] xor_ln896_12_fu_392_p2;
wire   [0:0] and_ln891_fu_362_p2;
wire   [0:0] or_ln896_fu_398_p2;
wire   [0:0] xor_ln896_fu_404_p2;
wire   [0:0] overflow_fu_386_p2;
wire   [0:0] underflow_fu_410_p2;
wire   [0:0] or_ln346_fu_424_p2;
wire   [23:0] select_ln346_13_fu_416_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_done_reg = 1'b0;
end

unsw_linear_transformer_unsw_linear_transformer_Pipeline_VITIS_LOOP_140_11_LAYERS_0_ATTENTION_KEY_WEIdEe #(
    .DataWidth( 11 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
LAYERS_0_ATTENTION_KEY_WEIGHT_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LAYERS_0_ATTENTION_KEY_WEIGHT_V_address0),
    .ce0(LAYERS_0_ATTENTION_KEY_WEIGHT_V_ce0),
    .q0(LAYERS_0_ATTENTION_KEY_WEIGHT_V_q0)
);

unsw_linear_transformer_mul_mul_15s_20s_35_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 20 ),
    .dout_WIDTH( 35 ))
mul_mul_15s_20s_35_4_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shl_ln838_5_fu_199_p3),
    .din1(r_V_7_fu_191_p3),
    .ce(1'b1),
    .dout(grp_fu_447_p2)
);

unsw_linear_transformer_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln140_fu_144_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            input_feature_2_fu_82 <= add_ln140_fu_150_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            input_feature_2_fu_82 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            lhs_fu_78 <= 24'd0;
        end else if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
            lhs_fu_78 <= key_sum_V_fu_430_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln140_reg_469 <= icmp_ln140_fu_144_p2;
        icmp_ln140_reg_469_pp0_iter1_reg <= icmp_ln140_reg_469;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        icmp_ln140_reg_469_pp0_iter2_reg <= icmp_ln140_reg_469_pp0_iter1_reg;
        icmp_ln140_reg_469_pp0_iter3_reg <= icmp_ln140_reg_469_pp0_iter2_reg;
        r_V_reg_493 <= grp_fu_447_p2;
        tmp_reg_499 <= grp_fu_447_p2[32'd13];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        LAYERS_0_ATTENTION_KEY_WEIGHT_V_ce0 = 1'b1;
    end else begin
        LAYERS_0_ATTENTION_KEY_WEIGHT_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln140_fu_144_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_input_feature = 5'd0;
    end else begin
        ap_sig_allocacmp_input_feature = input_feature_2_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        embedded_V_ce0 = 1'b1;
    end else begin
        embedded_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln140_reg_469_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        key_sum_V_4_out_ap_vld = 1'b1;
    end else begin
        key_sum_V_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LAYERS_0_ATTENTION_KEY_WEIGHT_V_address0 = zext_ln837_17_fu_170_p1;

assign Range2_all_ones_fu_310_p3 = ret_V_fu_243_p2[32'd38];

assign add_ln1347_9_fu_249_p2 = ($signed(lhs_5_fu_225_p3) + $signed(sext_ln1347_8_fu_240_p1));

assign add_ln140_fu_150_p2 = (ap_sig_allocacmp_input_feature + 5'd1);

assign add_ln142_fu_175_p2 = (zext_ln142 + zext_ln837_fu_156_p1);

assign add_ln837_4_fu_164_p2 = (zext_ln837_6 + zext_ln837_16_fu_160_p1);

assign and_ln891_fu_362_p2 = (carry_15_fu_304_p2 & Range2_all_ones_fu_310_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign carry_15_fu_304_p2 = (xor_ln896_5_fu_298_p2 & p_Result_36_fu_273_p3);

assign deleted_ones_fu_356_p2 = (or_ln890_fu_350_p2 & Range2_all_ones_fu_310_p3);

assign deleted_zeros_fu_330_p2 = (or_ln888_fu_324_p2 ^ Range2_all_ones_fu_310_p3);

assign embedded_V_address0 = zext_ln142_1_fu_181_p1;

assign icmp_ln140_fu_144_p2 = ((ap_sig_allocacmp_input_feature == 5'd16) ? 1'b1 : 1'b0);

assign key_sum_V_3_fu_263_p4 = {{add_ln1347_9_fu_249_p2[37:14]}};

assign key_sum_V_4_fu_284_p2 = (zext_ln377_fu_281_p1 + key_sum_V_3_fu_263_p4);

assign key_sum_V_4_out = lhs_fu_78;

assign key_sum_V_fu_430_p3 = ((or_ln346_fu_424_p2[0:0] == 1'b1) ? select_ln346_13_fu_416_p3 : key_sum_V_4_fu_284_p2);

assign lhs_5_fu_225_p3 = {{lhs_fu_78}, {14'd0}};

assign or_ln346_fu_424_p2 = (underflow_fu_410_p2 | overflow_fu_386_p2);

assign or_ln888_fu_324_p2 = (xor_ln888_4_fu_318_p2 | p_Result_37_fu_290_p3);

assign or_ln890_fu_350_p2 = (xor_ln890_fu_344_p2 | or_ln888_fu_324_p2);

assign or_ln895_fu_374_p2 = (xor_ln895_10_fu_368_p2 | p_Result_37_fu_290_p3);

assign or_ln896_fu_398_p2 = (xor_ln896_5_fu_298_p2 | xor_ln896_12_fu_392_p2);

assign overflow_fu_386_p2 = (xor_ln895_11_fu_380_p2 & or_ln895_fu_374_p2);

assign p_Result_36_fu_273_p3 = add_ln1347_9_fu_249_p2[32'd37];

assign p_Result_37_fu_290_p3 = key_sum_V_4_fu_284_p2[32'd23];

assign p_Result_s_fu_255_p3 = ret_V_fu_243_p2[32'd38];

assign r_V_7_fu_191_p3 = {{embedded_V_q0}, {4'd0}};

assign ret_V_fu_243_p2 = ($signed(sext_ln1347_6_fu_233_p1) + $signed(sext_ln1347_7_fu_237_p1));

assign select_ln346_13_fu_416_p3 = ((overflow_fu_386_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign sext_ln1347_6_fu_233_p1 = lhs_5_fu_225_p3;

assign sext_ln1347_7_fu_237_p1 = r_V_reg_493;

assign sext_ln1347_8_fu_240_p1 = r_V_reg_493;

assign shl_ln838_5_fu_199_p3 = {{LAYERS_0_ATTENTION_KEY_WEIGHT_V_q0}, {4'd0}};

assign tmp_49_fu_336_p3 = ret_V_fu_243_p2[32'd38];

assign underflow_fu_410_p2 = (xor_ln896_fu_404_p2 & p_Result_s_fu_255_p3);

assign xor_ln888_4_fu_318_p2 = (p_Result_36_fu_273_p3 ^ 1'd1);

assign xor_ln890_fu_344_p2 = (tmp_49_fu_336_p3 ^ 1'd1);

assign xor_ln895_10_fu_368_p2 = (deleted_zeros_fu_330_p2 ^ 1'd1);

assign xor_ln895_11_fu_380_p2 = (p_Result_s_fu_255_p3 ^ 1'd1);

assign xor_ln896_12_fu_392_p2 = (deleted_ones_fu_356_p2 ^ 1'd1);

assign xor_ln896_5_fu_298_p2 = (p_Result_37_fu_290_p3 ^ 1'd1);

assign xor_ln896_fu_404_p2 = (or_ln896_fu_398_p2 ^ and_ln891_fu_362_p2);

assign zext_ln142_1_fu_181_p1 = add_ln142_fu_175_p2;

assign zext_ln377_fu_281_p1 = tmp_reg_499;

assign zext_ln837_16_fu_160_p1 = ap_sig_allocacmp_input_feature;

assign zext_ln837_17_fu_170_p1 = add_ln837_4_fu_164_p2;

assign zext_ln837_fu_156_p1 = ap_sig_allocacmp_input_feature;

endmodule //unsw_linear_transformer_unsw_linear_transformer_Pipeline_VITIS_LOOP_140_11
