set SynModuleInfo {
  {SRCNAME transformer_for_sample_Pipeline_1 MODELNAME transformer_for_sample_Pipeline_1 RTLNAME transformer_transformer_for_sample_Pipeline_1
    SUBMODULES {
      {MODELNAME transformer_flow_control_loop_pipe_sequential_init RTLNAME transformer_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME transformer_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME transformer_for_sample_Pipeline_2 MODELNAME transformer_for_sample_Pipeline_2 RTLNAME transformer_transformer_for_sample_Pipeline_2}
  {SRCNAME transformer_for_sample_Pipeline_3 MODELNAME transformer_for_sample_Pipeline_3 RTLNAME transformer_transformer_for_sample_Pipeline_3}
  {SRCNAME transformer_for_sample_Pipeline_4 MODELNAME transformer_for_sample_Pipeline_4 RTLNAME transformer_transformer_for_sample_Pipeline_4}
  {SRCNAME transformer_for_sample_Pipeline_5 MODELNAME transformer_for_sample_Pipeline_5 RTLNAME transformer_transformer_for_sample_Pipeline_5}
  {SRCNAME transformer_for_sample_Pipeline_6 MODELNAME transformer_for_sample_Pipeline_6 RTLNAME transformer_transformer_for_sample_Pipeline_6}
  {SRCNAME transformer_for_sample_Pipeline_7 MODELNAME transformer_for_sample_Pipeline_7 RTLNAME transformer_transformer_for_sample_Pipeline_7}
  {SRCNAME transformer_for_sample_Pipeline_8 MODELNAME transformer_for_sample_Pipeline_8 RTLNAME transformer_transformer_for_sample_Pipeline_8}
  {SRCNAME transformer_for_sample_Pipeline_9 MODELNAME transformer_for_sample_Pipeline_9 RTLNAME transformer_transformer_for_sample_Pipeline_9}
  {SRCNAME transformer_for_sample_Pipeline_10 MODELNAME transformer_for_sample_Pipeline_10 RTLNAME transformer_transformer_for_sample_Pipeline_10}
  {SRCNAME transformer_for_sample_Pipeline_11 MODELNAME transformer_for_sample_Pipeline_11 RTLNAME transformer_transformer_for_sample_Pipeline_11}
  {SRCNAME transformer_for_sample_Pipeline_12 MODELNAME transformer_for_sample_Pipeline_12 RTLNAME transformer_transformer_for_sample_Pipeline_12}
  {SRCNAME transformer_for_sample_Pipeline_13 MODELNAME transformer_for_sample_Pipeline_13 RTLNAME transformer_transformer_for_sample_Pipeline_13}
  {SRCNAME transformer_for_sample_Pipeline_front_linear_i_front_linear_j MODELNAME transformer_for_sample_Pipeline_front_linear_i_front_linear_j RTLNAME transformer_transformer_for_sample_Pipeline_front_linear_i_front_linear_j
    SUBMODULES {
      {MODELNAME transformer_transformer_for_sample_Pipeline_front_linear_i_front_linear_j_FRONT_LINEAR_WEbkb RTLNAME transformer_transformer_for_sample_Pipeline_front_linear_i_front_linear_j_FRONT_LINEAR_WEbkb BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_front_linear_i_front_linear_j_FRONT_LINEAR_WEcud RTLNAME transformer_transformer_for_sample_Pipeline_front_linear_i_front_linear_j_FRONT_LINEAR_WEcud BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_front_linear_i_front_linear_j_FRONT_LINEAR_BIdEe RTLNAME transformer_transformer_for_sample_Pipeline_front_linear_i_front_linear_j_FRONT_LINEAR_BIdEe BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME transformer_for_sample_Pipeline_qkv_i_qkv_j MODELNAME transformer_for_sample_Pipeline_qkv_i_qkv_j RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j
    SUBMODULES {
      {MODELNAME transformer_fcmp_32ns_32ns_1_2_no_dsp_1 RTLNAME transformer_fcmp_32ns_32ns_1_2_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME transformer_fexp_32ns_32ns_32_10_full_dsp_1 RTLNAME transformer_fexp_32ns_32ns_32_10_full_dsp_1 BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 9 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFeOg RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFeOg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFfYi RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFfYi BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFg8j RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFg8j BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFhbi RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFhbi BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFibs RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFibs BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFjbC RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFjbC BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFkbM RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFkbM BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFlbW RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFlbW BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFmb6 RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFmb6 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFncg RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFncg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFocq RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFocq BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFpcA RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFpcA BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFqcK RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFqcK BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFrcU RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFrcU BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFsc4 RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFsc4 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFtde RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFtde BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFudo RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFudo BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFvdy RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFvdy BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFwdI RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFwdI BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFxdS RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFxdS BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFyd2 RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFyd2 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFzec RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFzec BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFAem RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFAem BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFBew RTLNAME transformer_transformer_for_sample_Pipeline_qkv_i_qkv_j_TRANSFORMER_ENCODER_LAYERS_0_SELFBew BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME transformer_for_sample_Pipeline_transpose_value_i_transpose_value_j MODELNAME transformer_for_sample_Pipeline_transpose_value_i_transpose_value_j RTLNAME transformer_transformer_for_sample_Pipeline_transpose_value_i_transpose_value_j}
  {SRCNAME transformer_for_sample_Pipeline_kv_i_kv_j MODELNAME transformer_for_sample_Pipeline_kv_i_kv_j RTLNAME transformer_transformer_for_sample_Pipeline_kv_i_kv_j}
  {SRCNAME transformer_for_sample_Pipeline_sum_k_j MODELNAME transformer_for_sample_Pipeline_sum_k_j RTLNAME transformer_transformer_for_sample_Pipeline_sum_k_j}
  {SRCNAME transformer_for_sample_Pipeline_normalizer_i MODELNAME transformer_for_sample_Pipeline_normalizer_i RTLNAME transformer_transformer_for_sample_Pipeline_normalizer_i
    SUBMODULES {
      {MODELNAME transformer_fdiv_32ns_32ns_32_16_no_dsp_1 RTLNAME transformer_fdiv_32ns_32ns_32_16_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 15 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME transformer_for_sample_Pipeline_numerator_i MODELNAME transformer_for_sample_Pipeline_numerator_i RTLNAME transformer_transformer_for_sample_Pipeline_numerator_i}
  {SRCNAME transformer_for_sample_Pipeline_o_proj_i_o_proj_j MODELNAME transformer_for_sample_Pipeline_o_proj_i_o_proj_j RTLNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j
    SUBMODULES {
      {MODELNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_CeG RTLNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_CeG BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_DeQ RTLNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_DeQ BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_Ee0 RTLNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_Ee0 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_Ffa RTLNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_Ffa BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_Gfk RTLNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_Gfk BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_Hfu RTLNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_Hfu BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_IfE RTLNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_IfE BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_JfO RTLNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_JfO BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_KfY RTLNAME transformer_transformer_for_sample_Pipeline_o_proj_i_o_proj_j_TRANSFORMER_ENCODER_LAYERS_KfY BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME transformer_for_sample_Pipeline_ff1_i_ff1_j MODELNAME transformer_for_sample_Pipeline_ff1_i_ff1_j RTLNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j
    SUBMODULES {
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINELf8 RTLNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINELf8 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINEMgi RTLNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINEMgi BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINENgs RTLNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINENgs BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINEOgC RTLNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINEOgC BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINEPgM RTLNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINEPgM BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINEQgW RTLNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINEQgW BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINERg6 RTLNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINERg6 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINEShg RTLNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINEShg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINEThq RTLNAME transformer_transformer_for_sample_Pipeline_ff1_i_ff1_j_TRANSFORMER_ENCODER_LAYERS_0_LINEThq BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME transformer_for_sample_Pipeline_ff2_i_ff2_j MODELNAME transformer_for_sample_Pipeline_ff2_i_ff2_j RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j
    SUBMODULES {
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEUhA RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEUhA BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEVhK RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEVhK BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEWhU RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEWhU BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEXh4 RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEXh4 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEYie RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEYie BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEZio RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEZio BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE0iy RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE0iy BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE1iI RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE1iI BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE2iS RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE2iS BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE3i2 RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE3i2 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE4jc RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE4jc BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE5jm RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE5jm BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE6jw RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE6jw BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE7jG RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE7jG BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE8jQ RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE8jQ BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE9j0 RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINE9j0 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEbak RTLNAME transformer_transformer_for_sample_Pipeline_ff2_i_ff2_j_TRANSFORMER_ENCODER_LAYERS_0_LINEbak BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME transformer_for_sample_Pipeline_final_i MODELNAME transformer_for_sample_Pipeline_final_i RTLNAME transformer_transformer_for_sample_Pipeline_final_i}
  {SRCNAME transformer_for_sample MODELNAME transformer_for_sample RTLNAME transformer_transformer_for_sample
    SUBMODULES {
      {MODELNAME transformer_fadd_32ns_32ns_32_5_full_dsp_1 RTLNAME transformer_fadd_32ns_32ns_32_5_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME transformer_fmul_32ns_32ns_32_4_max_dsp_1 RTLNAME transformer_fmul_32ns_32ns_32_4_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_front_RAM_1WNR_AUTO_1R1W RTLNAME transformer_transformer_for_sample_front_RAM_1WNR_AUTO_1R1W BINDTYPE storage TYPE ram_1wnr IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_value_RAM_AUTO_1R1W RTLNAME transformer_transformer_for_sample_value_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_kv_RAM_AUTO_1R1W RTLNAME transformer_transformer_for_sample_kv_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_sum_k_RAM_AUTO_1R1W RTLNAME transformer_transformer_for_sample_sum_k_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_normalizer_RAM_AUTO_1R1W RTLNAME transformer_transformer_for_sample_normalizer_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_values_new_RAM_AUTO_1R1W RTLNAME transformer_transformer_for_sample_values_new_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME transformer_transformer_for_sample_ff1_RAM_1WNR_AUTO_1R1W RTLNAME transformer_transformer_for_sample_ff1_RAM_1WNR_AUTO_1R1W BINDTYPE storage TYPE ram_1wnr IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME transformer MODELNAME transformer RTLNAME transformer IS_TOP 1
    SUBMODULES {
      {MODELNAME transformer_gmem0_m_axi RTLNAME transformer_gmem0_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME transformer_gmem1_m_axi RTLNAME transformer_gmem1_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME transformer_control_s_axi RTLNAME transformer_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
