-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity unsw_linear_transformer_unsw_linear_transformer_Pipeline_VITIS_LOOP_87_1_VITIS_LOOP_88_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_fp_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_fp_V_ce0 : OUT STD_LOGIC;
    input_fp_V_we0 : OUT STD_LOGIC;
    input_fp_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    grp_fu_3353_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_3353_p_dout0 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_3353_p_ce : OUT STD_LOGIC );
end;


architecture behav of unsw_linear_transformer_unsw_linear_transformer_Pipeline_VITIS_LOOP_87_1_VITIS_LOOP_88_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_C0 : STD_LOGIC_VECTOR (7 downto 0) := "11000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_A : STD_LOGIC_VECTOR (11 downto 0) := "000000001010";
    constant ap_const_lv12_FF6 : STD_LOGIC_VECTOR (11 downto 0) := "111111110110";
    constant ap_const_lv12_36 : STD_LOGIC_VECTOR (11 downto 0) := "000000110110";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv12_6 : STD_LOGIC_VECTOR (11 downto 0) := "000000000110";
    constant ap_const_lv12_C01 : STD_LOGIC_VECTOR (11 downto 0) := "110000000001";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv12_FF5 : STD_LOGIC_VECTOR (11 downto 0) := "111111110101";
    constant ap_const_lv12_2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv12_5 : STD_LOGIC_VECTOR (11 downto 0) := "000000000101";
    constant ap_const_lv12_7 : STD_LOGIC_VECTOR (11 downto 0) := "000000000111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv54_3FFFFFFFFFFFFF : STD_LOGIC_VECTOR (53 downto 0) := "111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln87_fu_181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln89_fu_261_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln89_reg_968 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln89_2_fu_288_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln89_2_reg_973 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln89_2_reg_973_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln89_2_reg_973_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln89_2_reg_973_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln89_2_reg_973_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln89_2_reg_973_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln89_2_reg_973_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln89_2_reg_973_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal input_r_load_reg_983 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_r_load_reg_983_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal input_r_load_reg_983_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal input_r_load_reg_983_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln89_fu_292_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_9_reg_994 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_reg_994_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_reg_994_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_reg_994_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal exp_tmp_reg_1003 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln554_fu_322_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln554_reg_1008 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln560_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln560_reg_1013 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln560_reg_1013_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln560_reg_1013_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln560_reg_1013_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln560_reg_1013_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln455_fu_332_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln455_reg_1019 : STD_LOGIC_VECTOR (11 downto 0);
    signal man_V_fu_352_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_reg_1024 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_reg_1024_pp0_iter6_reg : STD_LOGIC_VECTOR (53 downto 0);
    signal F2_fu_359_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_reg_1031 : STD_LOGIC_VECTOR (11 downto 0);
    signal QUAN_INC_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal QUAN_INC_reg_1039 : STD_LOGIC_VECTOR (0 downto 0);
    signal QUAN_INC_reg_1039_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sh_amt_fu_383_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sh_amt_reg_1045 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln572_fu_391_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln572_reg_1051 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln572_reg_1051_pp0_iter6_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln580_fu_395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln580_reg_1057 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln580_reg_1057_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln592_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln592_reg_1062 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln592_reg_1062_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pos1_fu_417_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal pos1_reg_1067 : STD_LOGIC_VECTOR (11 downto 0);
    signal pos1_reg_1067_pp0_iter6_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal pos1_reg_1067_pp0_iter7_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_159_reg_1074 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_159_reg_1074_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal lD_fu_435_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal lD_reg_1079 : STD_LOGIC_VECTOR (0 downto 0);
    signal lD_reg_1079_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln570_fu_448_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln570_reg_1084 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln571_fu_451_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln571_reg_1089 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_6_fu_489_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_6_reg_1095 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln580_fu_497_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln580_reg_1101 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln566_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln566_reg_1106 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln600_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln600_reg_1111 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln600_reg_1111_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pos2_fu_526_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal pos2_reg_1116 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln624_fu_535_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln624_reg_1124 : STD_LOGIC_VECTOR (53 downto 0);
    signal Range2_V_1_fu_539_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal Range2_V_1_reg_1129 : STD_LOGIC_VECTOR (53 downto 0);
    signal p_Val2_8_fu_626_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_8_reg_1135 : STD_LOGIC_VECTOR (15 downto 0);
    signal carry_2_fu_640_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_2_reg_1140 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_12_reg_1147 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_2_fu_702_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_2_reg_1154 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_1_fu_722_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_1_reg_1159 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_fu_760_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_reg_1164 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_2_fu_768_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_2_reg_1171 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln302_fu_929_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln302_reg_1176 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal f_fu_122 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln88_fu_267_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_f_load : STD_LOGIC_VECTOR (4 downto 0);
    signal s_fu_126 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln87_1_fu_219_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_s_load : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_fu_130 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln87_1_fu_187_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln88_fu_205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln87_fu_199_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln89_fu_227_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_7_fu_239_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_4_fu_231_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln89_fu_247_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln87_fu_211_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln89_fu_251_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln89_1_fu_257_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ireg_fu_296_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln544_fu_300_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal p_Result_10_fu_335_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln558_fu_342_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_1_fu_346_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal add_ln570_fu_371_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln570_fu_377_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_155_fu_401_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln607_fu_423_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_461_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln575_fu_476_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln575_fu_480_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln574_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln575_fu_485_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln577_fu_468_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln601_fu_507_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal exp_fu_443_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln601_fu_514_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln624_fu_531_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln580_fu_544_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln570cast_fu_554_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_s_fu_547_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal qb_fu_562_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln377_fu_575_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_7_fu_579_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_157_fu_584_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln571_fu_604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln566_fu_609_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln571_fu_598_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln592_fu_622_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln593_fu_557_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln566_fu_614_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_11_fu_568_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln378_fu_592_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln365_fu_634_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln610_1_fu_659_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_fu_679_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_160_fu_689_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln620_1_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_fu_684_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_1_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln620_fu_669_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_3_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_4_fu_664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln630_fu_728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln631_fu_739_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln628_fu_710_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_fu_716_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln631_fu_744_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln630_fu_733_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln631_1_fu_752_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_161_fu_786_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln642_fu_793_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln642_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln643_fu_809_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln610_fu_776_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_fu_803_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln610_fu_819_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln610_fu_831_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln546_fu_841_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln643_fu_813_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln610_1_fu_836_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_781_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln647_fu_854_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln647_fu_860_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln647_fu_866_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln647_1_fu_871_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_2_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln648_fu_882_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_1_fu_846_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln648_fu_887_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_893_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_876_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln302_fu_899_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln560_fu_913_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln302_fu_918_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln302_1_fu_924_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln346_fu_905_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component unsw_linear_transformer_fpext_32ns_64_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component unsw_linear_transformer_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component unsw_linear_transformer_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    f_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln87_fu_181_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    f_fu_122 <= add_ln88_fu_267_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    f_fu_122 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln87_fu_181_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_130 <= add_ln87_1_fu_187_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_130 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    s_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln87_fu_181_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    s_fu_126 <= select_ln87_1_fu_219_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    s_fu_126 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln560_reg_1013 = ap_const_lv1_0))) then
                F2_reg_1031 <= F2_fu_359_p2;
                QUAN_INC_reg_1039 <= QUAN_INC_fu_365_p2;
                icmp_ln580_reg_1057 <= icmp_ln580_fu_395_p2;
                icmp_ln592_reg_1062 <= icmp_ln592_fu_411_p2;
                lD_reg_1079 <= lD_fu_435_p3;
                man_V_reg_1024 <= man_V_fu_352_p3;
                pos1_reg_1067 <= pos1_fu_417_p2;
                sh_amt_reg_1045 <= sh_amt_fu_383_p3;
                tmp_159_reg_1074 <= pos1_fu_417_p2(11 downto 11);
                trunc_ln572_reg_1051 <= trunc_ln572_fu_391_p1;
                    zext_ln455_reg_1019(10 downto 0) <= zext_ln455_fu_332_p1(10 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                QUAN_INC_reg_1039_pp0_iter6_reg <= QUAN_INC_reg_1039;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                exp_tmp_reg_1003 <= ireg_fu_296_p1(62 downto 52);
                icmp_ln560_reg_1013 <= icmp_ln560_fu_326_p2;
                icmp_ln560_reg_1013_pp0_iter5_reg <= icmp_ln560_reg_1013;
                icmp_ln560_reg_1013_pp0_iter6_reg <= icmp_ln560_reg_1013_pp0_iter5_reg;
                icmp_ln560_reg_1013_pp0_iter7_reg <= icmp_ln560_reg_1013_pp0_iter6_reg;
                icmp_ln560_reg_1013_pp0_iter8_reg <= icmp_ln560_reg_1013_pp0_iter7_reg;
                icmp_ln580_reg_1057_pp0_iter6_reg <= icmp_ln580_reg_1057;
                icmp_ln592_reg_1062_pp0_iter6_reg <= icmp_ln592_reg_1062;
                icmp_ln600_reg_1111_pp0_iter7_reg <= icmp_ln600_reg_1111;
                input_r_load_reg_983 <= input_r_q0;
                input_r_load_reg_983_pp0_iter3_reg <= input_r_load_reg_983;
                input_r_load_reg_983_pp0_iter4_reg <= input_r_load_reg_983_pp0_iter3_reg;
                input_r_load_reg_983_pp0_iter5_reg <= input_r_load_reg_983_pp0_iter4_reg;
                lD_reg_1079_pp0_iter6_reg <= lD_reg_1079;
                man_V_reg_1024_pp0_iter6_reg <= man_V_reg_1024;
                p_Result_9_reg_994 <= ireg_fu_296_p1(63 downto 63);
                p_Result_9_reg_994_pp0_iter5_reg <= p_Result_9_reg_994;
                p_Result_9_reg_994_pp0_iter6_reg <= p_Result_9_reg_994_pp0_iter5_reg;
                p_Result_9_reg_994_pp0_iter7_reg <= p_Result_9_reg_994_pp0_iter6_reg;
                pos1_reg_1067_pp0_iter6_reg <= pos1_reg_1067;
                pos1_reg_1067_pp0_iter7_reg <= pos1_reg_1067_pp0_iter6_reg;
                tmp_159_reg_1074_pp0_iter6_reg <= tmp_159_reg_1074;
                trunc_ln554_reg_1008 <= trunc_ln554_fu_322_p1;
                trunc_ln572_reg_1051_pp0_iter6_reg <= trunc_ln572_reg_1051;
                    zext_ln89_2_reg_973_pp0_iter2_reg(7 downto 0) <= zext_ln89_2_reg_973(7 downto 0);
                    zext_ln89_2_reg_973_pp0_iter3_reg(7 downto 0) <= zext_ln89_2_reg_973_pp0_iter2_reg(7 downto 0);
                    zext_ln89_2_reg_973_pp0_iter4_reg(7 downto 0) <= zext_ln89_2_reg_973_pp0_iter3_reg(7 downto 0);
                    zext_ln89_2_reg_973_pp0_iter5_reg(7 downto 0) <= zext_ln89_2_reg_973_pp0_iter4_reg(7 downto 0);
                    zext_ln89_2_reg_973_pp0_iter6_reg(7 downto 0) <= zext_ln89_2_reg_973_pp0_iter5_reg(7 downto 0);
                    zext_ln89_2_reg_973_pp0_iter7_reg(7 downto 0) <= zext_ln89_2_reg_973_pp0_iter6_reg(7 downto 0);
                    zext_ln89_2_reg_973_pp0_iter8_reg(7 downto 0) <= zext_ln89_2_reg_973_pp0_iter7_reg(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln560_reg_1013_pp0_iter6_reg = ap_const_lv1_0))) then
                Range1_all_ones_2_reg_1164 <= Range1_all_ones_2_fu_760_p3;
                Range1_all_zeros_1_reg_1159 <= Range1_all_zeros_1_fu_722_p2;
                Range1_all_zeros_2_reg_1171 <= Range1_all_zeros_2_fu_768_p3;
                Range2_all_ones_2_reg_1154 <= Range2_all_ones_2_fu_702_p3;
                carry_2_reg_1140 <= carry_2_fu_640_p2;
                p_Result_12_reg_1147 <= p_Val2_8_fu_626_p3(15 downto 15);
                p_Val2_8_reg_1135 <= p_Val2_8_fu_626_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln560_reg_1013_pp0_iter5_reg = ap_const_lv1_0))) then
                Range2_V_1_reg_1129 <= Range2_V_1_fu_539_p2;
                icmp_ln566_reg_1106 <= icmp_ln566_fu_502_p2;
                icmp_ln571_reg_1089 <= icmp_ln571_fu_451_p2;
                icmp_ln600_reg_1111 <= icmp_ln600_fu_520_p2;
                p_Val2_6_reg_1095 <= p_Val2_6_fu_489_p3;
                pos2_reg_1116 <= pos2_fu_526_p2;
                sext_ln570_reg_1084 <= sext_ln570_fu_448_p1;
                    zext_ln624_reg_1124(31 downto 0) <= zext_ln624_fu_535_p1(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln580_reg_1057 = ap_const_lv1_0) and (icmp_ln560_reg_1013_pp0_iter5_reg = ap_const_lv1_0))) then
                add_ln580_reg_1101 <= add_ln580_fu_497_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln87_fu_181_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln89_reg_968 <= add_ln89_fu_261_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                    zext_ln89_2_reg_973(7 downto 0) <= zext_ln89_2_fu_288_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln560_reg_1013_pp0_iter7_reg = ap_const_lv1_0))) then
                select_ln302_reg_1176 <= select_ln302_fu_929_p3;
            end if;
        end if;
    end process;
    zext_ln89_2_reg_973(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln89_2_reg_973_pp0_iter2_reg(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln89_2_reg_973_pp0_iter3_reg(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln89_2_reg_973_pp0_iter4_reg(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln89_2_reg_973_pp0_iter5_reg(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln89_2_reg_973_pp0_iter6_reg(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln89_2_reg_973_pp0_iter7_reg(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln89_2_reg_973_pp0_iter8_reg(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln455_reg_1019(11) <= '0';
    zext_ln624_reg_1124(53 downto 32) <= "0000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    F2_fu_359_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln455_fu_332_p1));
    QUAN_INC_fu_365_p2 <= "1" when (signed(F2_fu_359_p2) > signed(ap_const_lv12_A)) else "0";
    Range1_all_ones_2_fu_760_p3 <= 
        Range1_all_ones_fu_716_p2 when (and_ln628_fu_710_p2(0) = '1') else 
        select_ln631_fu_744_p3;
    Range1_all_ones_3_fu_654_p2 <= (tmp_159_reg_1074_pp0_iter6_reg xor ap_const_lv1_1);
    Range1_all_ones_4_fu_664_p2 <= (lD_reg_1079_pp0_iter6_reg and icmp_ln610_1_fu_659_p2);
    Range1_all_ones_fu_716_p2 <= (Range2_all_ones_2_fu_702_p3 and Range1_all_ones_4_fu_664_p2);
    Range1_all_zeros_1_fu_722_p2 <= (ap_const_lv1_1 xor Range1_all_ones_4_fu_664_p2);
    Range1_all_zeros_2_fu_768_p3 <= 
        and_ln630_fu_733_p2 when (and_ln628_fu_710_p2(0) = '1') else 
        select_ln631_1_fu_752_p3;
    Range2_V_1_fu_539_p2 <= std_logic_vector(shift_right(unsigned(man_V_reg_1024),to_integer(unsigned('0' & zext_ln624_fu_535_p1(31-1 downto 0)))));
    Range2_all_ones_1_fu_696_p2 <= (tmp_160_fu_689_p3 xor ap_const_lv1_1);
    Range2_all_ones_2_fu_702_p3 <= 
        Range2_all_ones_fu_684_p2 when (icmp_ln620_1_fu_674_p2(0) = '1') else 
        Range2_all_ones_1_fu_696_p2;
    Range2_all_ones_fu_684_p2 <= "1" when (Range2_V_1_reg_1129 = r_V_fu_679_p2) else "0";
    add_ln570_fu_371_p2 <= std_logic_vector(unsigned(F2_fu_359_p2) + unsigned(ap_const_lv12_FF6));
    add_ln580_fu_497_p2 <= std_logic_vector(unsigned(F2_reg_1031) + unsigned(ap_const_lv12_FF5));
    add_ln601_fu_514_p2 <= std_logic_vector(unsigned(select_ln601_fu_507_p3) + unsigned(exp_fu_443_p2));
    add_ln87_1_fu_187_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv8_1));
    add_ln87_fu_199_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_s_load) + unsigned(ap_const_lv4_1));
    add_ln88_fu_267_p2 <= std_logic_vector(unsigned(select_ln87_fu_211_p3) + unsigned(ap_const_lv5_1));
    add_ln89_fu_261_p2 <= std_logic_vector(unsigned(sub_ln89_fu_251_p2) + unsigned(zext_ln89_1_fu_257_p1));
    and_ln302_1_fu_924_p2 <= (icmp_ln600_reg_1111_pp0_iter7_reg and and_ln302_fu_918_p2);
    and_ln302_fu_918_p2 <= (xor_ln560_fu_913_p2 and or_ln302_fu_899_p2);
    and_ln365_fu_634_p2 <= (xor_ln378_fu_592_p2 and p_Result_11_fu_568_p3);
    and_ln546_fu_841_p2 <= (p_Result_9_reg_994_pp0_iter7_reg and icmp_ln610_fu_776_p2);
    and_ln566_fu_609_p2 <= (xor_ln571_fu_604_p2 and QUAN_INC_reg_1039_pp0_iter6_reg);
    and_ln592_fu_622_p2 <= (icmp_ln592_reg_1062_pp0_iter6_reg and icmp_ln566_reg_1106);
    and_ln610_1_fu_836_p2 <= (p_Result_9_reg_994_pp0_iter7_reg and and_ln610_fu_831_p2);
    and_ln610_fu_831_p2 <= (xor_ln610_fu_819_p2 and p_Result_12_reg_1147);
    and_ln628_fu_710_p2 <= (icmp_ln620_fu_669_p2 and Range1_all_ones_3_fu_654_p2);
    and_ln630_fu_733_p2 <= (icmp_ln630_fu_728_p2 and Range1_all_zeros_1_fu_722_p2);
    and_ln642_fu_798_p2 <= (or_ln642_fu_793_p2 and Range2_all_ones_2_reg_1154);
    and_ln643_fu_809_p2 <= (carry_2_reg_1140 and Range1_all_ones_2_reg_1164);
    and_ln647_fu_860_p2 <= (xor_ln647_fu_854_p2 and icmp_ln610_fu_776_p2);
    and_ln648_fu_882_p2 <= (p_Result_12_reg_1147 and deleted_ones_2_fu_825_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln87_fu_181_p2)
    begin
        if (((icmp_ln87_fu_181_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_f_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, f_fu_122, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_f_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_f_load <= f_fu_122;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_130)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_130;
        end if; 
    end process;


    ap_sig_allocacmp_s_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, s_fu_126)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_s_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_s_load <= s_fu_126;
        end if; 
    end process;

    ashr_ln575_fu_480_p2 <= std_logic_vector(shift_right(signed(man_V_reg_1024),to_integer(unsigned('0' & zext_ln575_fu_476_p1(31-1 downto 0)))));
    bitcast_ln89_fu_292_p1 <= input_r_load_reg_983;
    carry_2_fu_640_p2 <= (and_ln566_fu_609_p2 and and_ln365_fu_634_p2);
    deleted_ones_2_fu_825_p2 <= (xor_ln610_fu_819_p2 or deleted_ones_fu_803_p3);
    deleted_ones_fu_803_p3 <= 
        and_ln642_fu_798_p2 when (carry_2_reg_1140(0) = '1') else 
        Range1_all_ones_2_reg_1164;
    deleted_zeros_fu_781_p3 <= 
        Range1_all_ones_2_reg_1164 when (carry_2_reg_1140(0) = '1') else 
        Range1_all_zeros_2_reg_1171;
    exp_fu_443_p2 <= std_logic_vector(unsigned(zext_ln455_reg_1019) + unsigned(ap_const_lv12_C01));
    grp_fu_3353_p_ce <= ap_const_logic_1;
    grp_fu_3353_p_din0 <= bitcast_ln89_fu_292_p1;
    icmp_ln560_fu_326_p2 <= "1" when (trunc_ln544_fu_300_p1 = ap_const_lv63_0) else "0";
    icmp_ln566_fu_502_p2 <= "1" when (signed(F2_reg_1031) < signed(ap_const_lv12_A)) else "0";
    icmp_ln571_fu_451_p2 <= "1" when (F2_reg_1031 = ap_const_lv12_A) else "0";
    icmp_ln574_fu_456_p2 <= "1" when (unsigned(sh_amt_reg_1045) < unsigned(ap_const_lv12_36)) else "0";
    icmp_ln580_fu_395_p2 <= "1" when (signed(add_ln570_fu_371_p2) > signed(ap_const_lv12_36)) else "0";
    icmp_ln592_fu_411_p2 <= "1" when (tmp_155_fu_401_p4 = ap_const_lv8_0) else "0";
    icmp_ln600_fu_520_p2 <= "1" when (signed(add_ln601_fu_514_p2) > signed(ap_const_lv12_5)) else "0";
    icmp_ln610_1_fu_659_p2 <= "1" when (unsigned(pos1_reg_1067_pp0_iter6_reg) < unsigned(ap_const_lv12_36)) else "0";
    icmp_ln610_fu_776_p2 <= "1" when (signed(pos1_reg_1067_pp0_iter7_reg) < signed(ap_const_lv12_36)) else "0";
    icmp_ln620_1_fu_674_p2 <= "1" when (unsigned(pos2_reg_1116) < unsigned(ap_const_lv12_36)) else "0";
    icmp_ln620_fu_669_p2 <= "1" when (signed(pos2_reg_1116) < signed(ap_const_lv12_36)) else "0";
    icmp_ln630_fu_728_p2 <= "1" when (Range2_V_1_reg_1129 = ap_const_lv54_0) else "0";
    icmp_ln631_fu_739_p2 <= "1" when (pos2_reg_1116 = ap_const_lv12_36) else "0";
    icmp_ln87_fu_181_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv8_C0) else "0";
    icmp_ln88_fu_205_p2 <= "1" when (ap_sig_allocacmp_f_load = ap_const_lv5_18) else "0";
    input_fp_V_address0 <= zext_ln89_2_reg_973_pp0_iter8_reg(8 - 1 downto 0);

    input_fp_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            input_fp_V_ce0 <= ap_const_logic_1;
        else 
            input_fp_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    input_fp_V_d0 <= 
        ap_const_lv16_0 when (icmp_ln560_reg_1013_pp0_iter8_reg(0) = '1') else 
        select_ln302_reg_1176;

    input_fp_V_we0_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            input_fp_V_we0 <= ap_const_logic_1;
        else 
            input_fp_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    input_r_address0 <= zext_ln89_2_fu_288_p1(8 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ireg_fu_296_p1 <= grp_fu_3353_p_dout0;
    lD_fu_435_p3 <= man_V_fu_352_p3(to_integer(unsigned(sext_ln607_fu_423_p1)) downto to_integer(unsigned(sext_ln607_fu_423_p1))) when (to_integer(unsigned(sext_ln607_fu_423_p1)) >= 0 and to_integer(unsigned(sext_ln607_fu_423_p1)) <=53) else "-";
    man_V_1_fu_346_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln558_fu_342_p1));
    man_V_fu_352_p3 <= 
        man_V_1_fu_346_p2 when (p_Result_9_reg_994(0) = '1') else 
        zext_ln558_fu_342_p1;
    neg_src_1_fu_846_p3 <= 
        xor_ln643_fu_813_p2 when (and_ln546_fu_841_p2(0) = '1') else 
        and_ln610_1_fu_836_p2;
    or_ln302_fu_899_p2 <= (underflow_fu_893_p2 or overflow_fu_876_p2);
    or_ln642_fu_793_p2 <= (tmp_161_fu_786_p3 or Range1_all_zeros_1_reg_1159);
    or_ln647_fu_866_p2 <= (p_Result_12_reg_1147 or and_ln647_fu_860_p2);
    overflow_fu_876_p2 <= (xor_ln647_1_fu_871_p2 and or_ln647_fu_866_p2);
    p_Result_10_fu_335_p3 <= (ap_const_lv1_1 & trunc_ln554_reg_1008);
    p_Result_11_fu_568_p3 <= p_Val2_6_reg_1095(15 downto 15);
    p_Result_s_fu_547_p3 <= man_V_reg_1024_pp0_iter6_reg(to_integer(unsigned(sext_ln580_fu_544_p1)) downto to_integer(unsigned(sext_ln580_fu_544_p1))) when (to_integer(unsigned(sext_ln580_fu_544_p1)) >= 0 and to_integer(unsigned(sext_ln580_fu_544_p1)) <=53) else "-";
    p_Val2_6_fu_489_p3 <= 
        trunc_ln575_fu_485_p1 when (icmp_ln574_fu_456_p2(0) = '1') else 
        select_ln577_fu_468_p3;
    p_Val2_7_fu_579_p2 <= std_logic_vector(unsigned(p_Val2_6_reg_1095) + unsigned(zext_ln377_fu_575_p1));
    p_Val2_8_fu_626_p3 <= 
        shl_ln593_fu_557_p2 when (and_ln592_fu_622_p2(0) = '1') else 
        select_ln566_fu_614_p3;
    pos1_fu_417_p2 <= std_logic_vector(unsigned(F2_fu_359_p2) + unsigned(ap_const_lv12_6));
    pos2_fu_526_p2 <= std_logic_vector(unsigned(F2_reg_1031) + unsigned(ap_const_lv12_7));
    qb_fu_562_p3 <= 
        p_Result_9_reg_994_pp0_iter6_reg when (icmp_ln580_reg_1057_pp0_iter6_reg(0) = '1') else 
        p_Result_s_fu_547_p3;
    r_V_fu_679_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv54_3FFFFFFFFFFFFF),to_integer(unsigned('0' & zext_ln624_reg_1124(31-1 downto 0)))));
    select_ln302_fu_929_p3 <= 
        select_ln346_fu_905_p3 when (and_ln302_1_fu_924_p2(0) = '1') else 
        p_Val2_8_reg_1135;
    select_ln346_fu_905_p3 <= 
        ap_const_lv16_7FFF when (overflow_fu_876_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln566_fu_614_p3 <= 
        p_Val2_7_fu_579_p2 when (and_ln566_fu_609_p2(0) = '1') else 
        select_ln571_fu_598_p3;
    select_ln571_fu_598_p3 <= 
        trunc_ln572_reg_1051_pp0_iter6_reg when (icmp_ln571_reg_1089(0) = '1') else 
        ap_const_lv16_0;
    select_ln577_fu_468_p3 <= 
        ap_const_lv16_FFFF when (tmp_fu_461_p3(0) = '1') else 
        ap_const_lv16_0;
    select_ln601_fu_507_p3 <= 
        ap_const_lv12_2 when (QUAN_INC_reg_1039(0) = '1') else 
        ap_const_lv12_1;
    select_ln631_1_fu_752_p3 <= 
        Range1_all_zeros_1_fu_722_p2 when (icmp_ln631_fu_739_p2(0) = '1') else 
        Range1_all_ones_3_fu_654_p2;
    select_ln631_fu_744_p3 <= 
        Range1_all_ones_4_fu_664_p2 when (icmp_ln631_fu_739_p2(0) = '1') else 
        Range1_all_ones_3_fu_654_p2;
    select_ln87_1_fu_219_p3 <= 
        add_ln87_fu_199_p2 when (icmp_ln88_fu_205_p2(0) = '1') else 
        ap_sig_allocacmp_s_load;
    select_ln87_fu_211_p3 <= 
        ap_const_lv5_0 when (icmp_ln88_fu_205_p2(0) = '1') else 
        ap_sig_allocacmp_f_load;
        sext_ln570_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sh_amt_reg_1045),32));

    sext_ln570cast_fu_554_p1 <= sext_ln570_reg_1084(16 - 1 downto 0);
        sext_ln580_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln580_reg_1101),32));

        sext_ln607_fu_423_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(pos1_fu_417_p2),32));

        sext_ln624_fu_531_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(pos2_fu_526_p2),32));

    sh_amt_fu_383_p3 <= 
        add_ln570_fu_371_p2 when (QUAN_INC_fu_365_p2(0) = '1') else 
        sub_ln570_fu_377_p2;
    shl_ln593_fu_557_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln572_reg_1051_pp0_iter6_reg),to_integer(unsigned('0' & sext_ln570cast_fu_554_p1(16-1 downto 0)))));
    sub_ln570_fu_377_p2 <= std_logic_vector(unsigned(ap_const_lv12_A) - unsigned(F2_fu_359_p2));
    sub_ln89_fu_251_p2 <= std_logic_vector(unsigned(tmp_4_fu_231_p3) - unsigned(zext_ln89_fu_247_p1));
    tmp_155_fu_401_p4 <= sh_amt_fu_383_p3(11 downto 4);
    tmp_157_fu_584_p3 <= p_Val2_7_fu_579_p2(15 downto 15);
    tmp_160_fu_689_p3 <= pos2_reg_1116(11 downto 11);
    tmp_161_fu_786_p3 <= pos1_reg_1067_pp0_iter7_reg(11 downto 11);
    tmp_4_fu_231_p3 <= (trunc_ln89_fu_227_p1 & ap_const_lv5_0);
    tmp_7_fu_239_p3 <= (select_ln87_1_fu_219_p3 & ap_const_lv3_0);
    tmp_fu_461_p3 <= input_r_load_reg_983_pp0_iter5_reg(31 downto 31);
    trunc_ln544_fu_300_p1 <= ireg_fu_296_p1(63 - 1 downto 0);
    trunc_ln554_fu_322_p1 <= ireg_fu_296_p1(52 - 1 downto 0);
    trunc_ln572_fu_391_p1 <= man_V_fu_352_p3(16 - 1 downto 0);
    trunc_ln575_fu_485_p1 <= ashr_ln575_fu_480_p2(16 - 1 downto 0);
    trunc_ln89_fu_227_p1 <= select_ln87_1_fu_219_p3(3 - 1 downto 0);
    underflow_fu_893_p2 <= (xor_ln648_fu_887_p2 and neg_src_1_fu_846_p3);
    xor_ln378_fu_592_p2 <= (tmp_157_fu_584_p3 xor ap_const_lv1_1);
    xor_ln560_fu_913_p2 <= (icmp_ln560_reg_1013_pp0_iter7_reg xor ap_const_lv1_1);
    xor_ln571_fu_604_p2 <= (icmp_ln571_reg_1089 xor ap_const_lv1_1);
    xor_ln610_fu_819_p2 <= (icmp_ln610_fu_776_p2 xor ap_const_lv1_1);
    xor_ln643_fu_813_p2 <= (ap_const_lv1_1 xor and_ln643_fu_809_p2);
    xor_ln647_1_fu_871_p2 <= (p_Result_9_reg_994_pp0_iter7_reg xor ap_const_lv1_1);
    xor_ln647_fu_854_p2 <= (deleted_zeros_fu_781_p3 xor ap_const_lv1_1);
    xor_ln648_fu_887_p2 <= (ap_const_lv1_1 xor and_ln648_fu_882_p2);
    zext_ln377_fu_575_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qb_fu_562_p3),16));
    zext_ln455_fu_332_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_tmp_reg_1003),12));
    zext_ln558_fu_342_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Result_10_fu_335_p3),54));
    zext_ln575_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln570_fu_448_p1),54));
    zext_ln624_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln624_fu_531_p1),54));
    zext_ln89_1_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln87_fu_211_p3),8));
    zext_ln89_2_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln89_reg_968),64));
    zext_ln89_fu_247_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_239_p3),8));
end behav;
