// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module unsw_linear_transformer_layer_norm_2d_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_6_0_0_0_Pipeline_VITIS_LO_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln837,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        sext_ln1348,
        variance_V_4_out,
        variance_V_4_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [6:0] zext_ln837;
output  [6:0] input_r_address0;
output   input_r_ce0;
input  [15:0] input_r_q0;
input  [15:0] sext_ln1348;
output  [23:0] variance_V_4_out;
output   variance_V_4_out_ap_vld;

reg ap_idle;
reg input_r_ce0;
reg variance_V_4_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln23_reg_503;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire  signed [16:0] sext_ln1348_cast_fu_130_p1;
reg  signed [16:0] sext_ln1348_cast_reg_498;
wire   [0:0] icmp_ln23_fu_147_p2;
wire   [15:0] select_ln302_fu_234_p3;
reg   [15:0] select_ln302_reg_512;
wire    ap_block_pp0_stage1_11001;
wire   [39:0] r_V_17_fu_253_p2;
reg   [39:0] r_V_17_reg_517;
reg   [0:0] tmp_141_reg_522;
wire   [39:0] ret_V_4_fu_282_p2;
reg   [39:0] ret_V_4_reg_527;
reg   [0:0] p_Result_150_reg_533;
reg   [0:0] p_Result_151_reg_539;
wire   [23:0] variance_V_4_fu_316_p2;
reg   [23:0] variance_V_4_reg_544;
reg   [0:0] p_Result_152_reg_549;
reg   [1:0] tmp_reg_555;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln25_1_fu_169_p1;
wire    ap_block_pp0_stage0;
reg   [23:0] lhs_V_fu_90;
wire   [23:0] variance_V_fu_467_p3;
wire    ap_loop_init;
wire    ap_block_pp0_stage1;
reg   [4:0] feature_fu_94;
wire   [4:0] add_ln23_fu_153_p2;
reg   [4:0] ap_sig_allocacmp_feature_4;
wire    ap_block_pp0_stage0_01001;
wire   [6:0] zext_ln25_fu_159_p1;
wire   [6:0] add_ln25_fu_163_p2;
wire  signed [16:0] sext_ln1348_1_fu_179_p1;
wire   [16:0] ret_V_fu_183_p2;
wire   [0:0] p_Result_s_fu_188_p3;
wire   [0:0] p_Result_149_fu_200_p3;
wire   [0:0] xor_ln895_fu_208_p2;
wire   [0:0] overflow_fu_214_p2;
wire   [0:0] xor_ln302_fu_220_p2;
wire   [15:0] select_ln346_fu_226_p3;
wire   [15:0] centered_V_fu_196_p1;
wire   [19:0] r_V_fu_242_p3;
wire  signed [19:0] r_V_17_fu_253_p0;
wire  signed [39:0] sext_ln1270_fu_249_p1;
wire  signed [19:0] r_V_17_fu_253_p1;
wire   [37:0] lhs_V_3_fu_270_p3;
wire  signed [39:0] sext_ln1347_fu_278_p1;
wire   [23:0] zext_ln377_fu_313_p1;
wire   [23:0] variance_V_3_fu_295_p4;
wire   [0:0] xor_ln896_fu_340_p2;
wire   [0:0] carry_41_fu_345_p2;
wire   [0:0] Range1_all_ones_fu_357_p2;
wire   [0:0] Range1_all_zeros_fu_362_p2;
wire   [0:0] tmp_144_fu_375_p3;
wire   [0:0] Range2_all_ones_fu_350_p3;
wire   [0:0] xor_ln890_fu_382_p2;
wire   [0:0] and_ln890_fu_388_p2;
wire   [0:0] deleted_zeros_fu_367_p3;
wire   [0:0] xor_ln895_24_fu_408_p2;
wire   [0:0] or_ln895_fu_414_p2;
wire   [0:0] xor_ln895_25_fu_419_p2;
wire   [0:0] deleted_ones_26_fu_394_p3;
wire   [0:0] xor_ln896_33_fu_430_p2;
wire   [0:0] and_ln891_fu_402_p2;
wire   [0:0] or_ln896_fu_436_p2;
wire   [0:0] xor_ln896_34_fu_442_p2;
wire   [0:0] overflow_25_fu_424_p2;
wire   [0:0] underflow_fu_448_p2;
wire   [0:0] or_ln346_fu_461_p2;
wire   [23:0] select_ln346_27_fu_453_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage0;
reg    ap_idle_pp0_0to0;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

unsw_linear_transformer_mul_20s_20s_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 20 ),
    .dout_WIDTH( 40 ))
mul_20s_20s_40_1_1_U67(
    .din0(r_V_17_fu_253_p0),
    .din1(r_V_17_fu_253_p1),
    .dout(r_V_17_fu_253_p2)
);

unsw_linear_transformer_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln23_fu_147_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            feature_fu_94 <= add_ln23_fu_153_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            feature_fu_94 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            lhs_V_fu_90 <= 24'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            lhs_V_fu_90 <= variance_V_fu_467_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln23_reg_503 <= icmp_ln23_fu_147_p2;
        r_V_17_reg_517 <= r_V_17_fu_253_p2;
        sext_ln1348_cast_reg_498 <= sext_ln1348_cast_fu_130_p1;
        tmp_141_reg_522 <= r_V_17_fu_253_p2[32'd13];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_Result_150_reg_533 <= ret_V_4_fu_282_p2[32'd39];
        p_Result_151_reg_539 <= ret_V_4_fu_282_p2[32'd37];
        p_Result_152_reg_549 <= variance_V_4_fu_316_p2[32'd23];
        ret_V_4_reg_527 <= ret_V_4_fu_282_p2;
        tmp_reg_555 <= {{ret_V_4_fu_282_p2[39:38]}};
        variance_V_4_reg_544 <= variance_V_4_fu_316_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln23_reg_503 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        select_ln302_reg_512 <= select_ln302_fu_234_p3;
    end
end

always @ (*) begin
    if (((icmp_ln23_reg_503 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln23_reg_503 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_feature_4 = 5'd0;
    end else begin
        ap_sig_allocacmp_feature_4 = feature_fu_94;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln23_reg_503 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        variance_V_4_out_ap_vld = 1'b1;
    end else begin
        variance_V_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Range1_all_ones_fu_357_p2 = ((tmp_reg_555 == 2'd3) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_362_p2 = ((tmp_reg_555 == 2'd0) ? 1'b1 : 1'b0);

assign Range2_all_ones_fu_350_p3 = ret_V_4_reg_527[32'd39];

assign add_ln23_fu_153_p2 = (ap_sig_allocacmp_feature_4 + 5'd1);

assign add_ln25_fu_163_p2 = (zext_ln837 + zext_ln25_fu_159_p1);

assign and_ln890_fu_388_p2 = (xor_ln890_fu_382_p2 & Range2_all_ones_fu_350_p3);

assign and_ln891_fu_402_p2 = (carry_41_fu_345_p2 & Range1_all_ones_fu_357_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign carry_41_fu_345_p2 = (xor_ln896_fu_340_p2 & p_Result_151_reg_539);

assign centered_V_fu_196_p1 = ret_V_fu_183_p2[15:0];

assign deleted_ones_26_fu_394_p3 = ((carry_41_fu_345_p2[0:0] == 1'b1) ? and_ln890_fu_388_p2 : Range1_all_ones_fu_357_p2);

assign deleted_zeros_fu_367_p3 = ((carry_41_fu_345_p2[0:0] == 1'b1) ? Range1_all_ones_fu_357_p2 : Range1_all_zeros_fu_362_p2);

assign icmp_ln23_fu_147_p2 = ((ap_sig_allocacmp_feature_4 == 5'd16) ? 1'b1 : 1'b0);

assign input_r_address0 = zext_ln25_1_fu_169_p1;

assign lhs_V_3_fu_270_p3 = {{lhs_V_fu_90}, {14'd0}};

assign or_ln346_fu_461_p2 = (underflow_fu_448_p2 | overflow_25_fu_424_p2);

assign or_ln895_fu_414_p2 = (xor_ln895_24_fu_408_p2 | p_Result_152_reg_549);

assign or_ln896_fu_436_p2 = (xor_ln896_fu_340_p2 | xor_ln896_33_fu_430_p2);

assign overflow_25_fu_424_p2 = (xor_ln895_25_fu_419_p2 & or_ln895_fu_414_p2);

assign overflow_fu_214_p2 = (xor_ln895_fu_208_p2 & p_Result_149_fu_200_p3);

assign p_Result_149_fu_200_p3 = ret_V_fu_183_p2[32'd15];

assign p_Result_s_fu_188_p3 = ret_V_fu_183_p2[32'd16];

assign r_V_17_fu_253_p0 = sext_ln1270_fu_249_p1;

assign r_V_17_fu_253_p1 = sext_ln1270_fu_249_p1;

assign r_V_fu_242_p3 = {{select_ln302_reg_512}, {4'd0}};

assign ret_V_4_fu_282_p2 = ($signed(sext_ln1347_fu_278_p1) + $signed(r_V_17_reg_517));

assign ret_V_fu_183_p2 = ($signed(sext_ln1348_1_fu_179_p1) - $signed(sext_ln1348_cast_reg_498));

assign select_ln302_fu_234_p3 = ((xor_ln302_fu_220_p2[0:0] == 1'b1) ? select_ln346_fu_226_p3 : centered_V_fu_196_p1);

assign select_ln346_27_fu_453_p3 = ((overflow_25_fu_424_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln346_fu_226_p3 = ((overflow_fu_214_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign sext_ln1270_fu_249_p1 = $signed(r_V_fu_242_p3);

assign sext_ln1347_fu_278_p1 = $signed(lhs_V_3_fu_270_p3);

assign sext_ln1348_1_fu_179_p1 = $signed(input_r_q0);

assign sext_ln1348_cast_fu_130_p1 = $signed(sext_ln1348);

assign tmp_144_fu_375_p3 = ret_V_4_reg_527[32'd38];

assign underflow_fu_448_p2 = (xor_ln896_34_fu_442_p2 & p_Result_150_reg_533);

assign variance_V_3_fu_295_p4 = {{ret_V_4_fu_282_p2[37:14]}};

assign variance_V_4_fu_316_p2 = (zext_ln377_fu_313_p1 + variance_V_3_fu_295_p4);

assign variance_V_4_out = lhs_V_fu_90;

assign variance_V_fu_467_p3 = ((or_ln346_fu_461_p2[0:0] == 1'b1) ? select_ln346_27_fu_453_p3 : variance_V_4_reg_544);

assign xor_ln302_fu_220_p2 = (p_Result_s_fu_188_p3 ^ p_Result_149_fu_200_p3);

assign xor_ln890_fu_382_p2 = (tmp_144_fu_375_p3 ^ 1'd1);

assign xor_ln895_24_fu_408_p2 = (deleted_zeros_fu_367_p3 ^ 1'd1);

assign xor_ln895_25_fu_419_p2 = (p_Result_150_reg_533 ^ 1'd1);

assign xor_ln895_fu_208_p2 = (p_Result_s_fu_188_p3 ^ 1'd1);

assign xor_ln896_33_fu_430_p2 = (deleted_ones_26_fu_394_p3 ^ 1'd1);

assign xor_ln896_34_fu_442_p2 = (or_ln896_fu_436_p2 ^ and_ln891_fu_402_p2);

assign xor_ln896_fu_340_p2 = (p_Result_152_reg_549 ^ 1'd1);

assign zext_ln25_1_fu_169_p1 = add_ln25_fu_163_p2;

assign zext_ln25_fu_159_p1 = ap_sig_allocacmp_feature_4;

assign zext_ln377_fu_313_p1 = tmp_141_reg_522;

endmodule //unsw_linear_transformer_layer_norm_2d_ap_fixed_ap_fixed_ap_fixed_ap_fixed_16_6_0_0_0_Pipeline_VITIS_LO_1
