// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module unsw_linear_transformer_unsw_linear_transformer_Pipeline_VITIS_LOOP_172_15_VITIS_LOOP_173_16_VITIS_LOOP_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        key_value_V_address0,
        key_value_V_ce0,
        key_value_V_we0,
        key_value_V_d0,
        key_V_address0,
        key_V_ce0,
        key_V_q0,
        value_V_address0,
        value_V_ce0,
        value_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] key_value_V_address0;
output   key_value_V_ce0;
output   key_value_V_we0;
output  [27:0] key_value_V_d0;
output  [6:0] key_V_address0;
output   key_V_ce0;
input  [15:0] key_V_q0;
output  [6:0] value_V_address0;
output   value_V_ce0;
input  [15:0] value_V_q0;

reg ap_idle;
reg key_value_V_ce0;
reg key_value_V_we0;
reg key_V_ce0;
reg value_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln172_fu_186_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] trunc_ln172_fu_235_p1;
reg   [3:0] trunc_ln172_reg_705;
wire   [0:0] or_ln173_fu_267_p2;
reg   [0:0] or_ln173_reg_710;
reg   [0:0] or_ln173_reg_710_pp0_iter2_reg;
wire   [4:0] select_ln173_1_fu_285_p3;
reg   [4:0] select_ln173_1_reg_715;
wire   [3:0] add_ln175_fu_327_p2;
reg   [3:0] add_ln175_reg_730;
wire   [7:0] add_ln180_fu_382_p2;
reg   [7:0] add_ln180_reg_735;
wire  signed [43:0] r_V_fu_412_p2;
reg  signed [43:0] r_V_reg_740;
reg   [0:0] tmp_reg_746;
wire   [0:0] icmp_ln175_1_fu_426_p2;
reg   [0:0] icmp_ln175_1_reg_751;
reg   [0:0] icmp_ln175_1_reg_751_pp0_iter3_reg;
reg   [7:0] key_value_V_addr_reg_755;
wire   [27:0] sum_V_fu_646_p3;
reg   [27:0] sum_V_reg_760;
wire   [63:0] zext_ln837_fu_311_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln837_13_fu_322_p1;
wire   [63:0] zext_ln180_3_fu_434_p1;
reg   [27:0] lhs_fu_88;
wire    ap_loop_init;
reg   [3:0] sequence_fu_92;
reg   [4:0] value_feature_fu_96;
reg   [8:0] indvar_flatten38_fu_100;
wire   [8:0] select_ln173_3_fu_339_p3;
reg   [4:0] key_feature_fu_104;
wire   [4:0] select_ln172_1_fu_227_p3;
reg   [11:0] indvar_flatten53_fu_108;
wire   [11:0] add_ln172_1_fu_192_p2;
wire   [0:0] icmp_ln173_fu_213_p2;
wire   [4:0] add_ln172_fu_207_p2;
wire   [0:0] icmp_ln175_fu_249_p2;
wire   [0:0] xor_ln172_fu_243_p2;
wire   [4:0] select_ln172_fu_219_p3;
wire   [0:0] and_ln172_fu_255_p2;
wire   [3:0] select_ln173_fu_273_p3;
wire   [4:0] add_ln173_fu_261_p2;
wire   [2:0] trunc_ln173_fu_281_p1;
wire   [6:0] tmp_8_fu_297_p3;
wire   [6:0] zext_ln180_fu_239_p1;
wire   [6:0] add_ln837_fu_305_p2;
wire   [6:0] zext_ln180_1_fu_293_p1;
wire   [6:0] add_ln837_4_fu_316_p2;
wire   [8:0] add_ln173_1_fu_333_p2;
wire   [7:0] tmp_s_fu_372_p3;
wire   [7:0] zext_ln180_2_fu_379_p1;
wire  signed [21:0] r_V_9_fu_388_p3;
wire  signed [21:0] shl_ln838_7_fu_396_p3;
wire   [27:0] select_ln173_2_fu_438_p3;
wire  signed [43:0] lhs_5_fu_445_p3;
wire  signed [44:0] sext_ln1347_fu_453_p1;
wire  signed [44:0] sext_ln1347_12_fu_457_p1;
wire   [44:0] ret_V_fu_460_p2;
wire   [43:0] add_ln1347_8_fu_466_p2;
wire   [27:0] zext_ln377_fu_497_p1;
wire   [27:0] sum_V_11_fu_479_p4;
wire   [27:0] sum_V_12_fu_500_p2;
wire   [0:0] p_Result_33_fu_506_p3;
wire   [0:0] p_Result_32_fu_489_p3;
wire   [0:0] xor_ln896_19_fu_514_p2;
wire   [0:0] xor_ln888_fu_534_p2;
wire   [0:0] Range2_all_ones_fu_526_p3;
wire   [0:0] or_ln888_fu_540_p2;
wire   [0:0] tmp_43_fu_552_p3;
wire   [0:0] xor_ln890_fu_560_p2;
wire   [0:0] or_ln890_fu_566_p2;
wire   [0:0] carry_13_fu_520_p2;
wire   [0:0] deleted_zeros_fu_546_p2;
wire   [0:0] xor_ln895_fu_584_p2;
wire   [0:0] p_Result_s_fu_471_p3;
wire   [0:0] or_ln895_fu_590_p2;
wire   [0:0] xor_ln895_13_fu_596_p2;
wire   [0:0] deleted_ones_fu_572_p2;
wire   [0:0] xor_ln896_fu_608_p2;
wire   [0:0] and_ln891_fu_578_p2;
wire   [0:0] or_ln896_fu_614_p2;
wire   [0:0] xor_ln896_20_fu_620_p2;
wire   [0:0] overflow_fu_602_p2;
wire   [0:0] underflow_fu_626_p2;
wire   [0:0] or_ln346_fu_640_p2;
wire   [27:0] select_ln346_fu_632_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_done_reg = 1'b0;
end

unsw_linear_transformer_mul_22s_22s_44_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 44 ))
mul_22s_22s_44_1_1_U34(
    .din0(shl_ln838_7_fu_396_p3),
    .din1(r_V_9_fu_388_p3),
    .dout(r_V_fu_412_p2)
);

unsw_linear_transformer_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten38_fu_100 <= 9'd0;
        end else if (((icmp_ln172_fu_186_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten38_fu_100 <= select_ln173_3_fu_339_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten53_fu_108 <= 12'd0;
        end else if (((icmp_ln172_fu_186_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten53_fu_108 <= add_ln172_1_fu_192_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            key_feature_fu_104 <= 5'd0;
        end else if (((icmp_ln172_fu_186_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            key_feature_fu_104 <= select_ln172_1_fu_227_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            lhs_fu_88 <= 28'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            lhs_fu_88 <= sum_V_fu_646_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            sequence_fu_92 <= 4'd0;
        end else if (((icmp_ln172_fu_186_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            sequence_fu_92 <= add_ln175_fu_327_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            value_feature_fu_96 <= 5'd0;
        end else if (((icmp_ln172_fu_186_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            value_feature_fu_96 <= select_ln173_1_fu_285_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln172_fu_186_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln175_reg_730 <= add_ln175_fu_327_p2;
        or_ln173_reg_710 <= or_ln173_fu_267_p2;
        select_ln173_1_reg_715 <= select_ln173_1_fu_285_p3;
        trunc_ln172_reg_705 <= trunc_ln172_fu_235_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln180_reg_735 <= add_ln180_fu_382_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln175_1_reg_751 <= icmp_ln175_1_fu_426_p2;
        icmp_ln175_1_reg_751_pp0_iter3_reg <= icmp_ln175_1_reg_751;
        key_value_V_addr_reg_755 <= zext_ln180_3_fu_434_p1;
        or_ln173_reg_710_pp0_iter2_reg <= or_ln173_reg_710;
        r_V_reg_740 <= r_V_fu_412_p2;
        sum_V_reg_760 <= sum_V_fu_646_p3;
        tmp_reg_746 <= r_V_fu_412_p2[32'd15];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (*) begin
    if (((icmp_ln172_fu_186_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        key_V_ce0 = 1'b1;
    end else begin
        key_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        key_value_V_ce0 = 1'b1;
    end else begin
        key_value_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln175_1_reg_751_pp0_iter3_reg == 1'd1))) begin
        key_value_V_we0 = 1'b1;
    end else begin
        key_value_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        value_V_ce0 = 1'b1;
    end else begin
        value_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Range2_all_ones_fu_526_p3 = ret_V_fu_460_p2[32'd44];

assign add_ln1347_8_fu_466_p2 = ($signed(lhs_5_fu_445_p3) + $signed(r_V_reg_740));

assign add_ln172_1_fu_192_p2 = (indvar_flatten53_fu_108 + 12'd1);

assign add_ln172_fu_207_p2 = (key_feature_fu_104 + 5'd1);

assign add_ln173_1_fu_333_p2 = (indvar_flatten38_fu_100 + 9'd1);

assign add_ln173_fu_261_p2 = (select_ln172_fu_219_p3 + 5'd1);

assign add_ln175_fu_327_p2 = (select_ln173_fu_273_p3 + 4'd1);

assign add_ln180_fu_382_p2 = (tmp_s_fu_372_p3 + zext_ln180_2_fu_379_p1);

assign add_ln837_4_fu_316_p2 = (tmp_8_fu_297_p3 + zext_ln180_1_fu_293_p1);

assign add_ln837_fu_305_p2 = (tmp_8_fu_297_p3 + zext_ln180_fu_239_p1);

assign and_ln172_fu_255_p2 = (xor_ln172_fu_243_p2 & icmp_ln175_fu_249_p2);

assign and_ln891_fu_578_p2 = (carry_13_fu_520_p2 & Range2_all_ones_fu_526_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign carry_13_fu_520_p2 = (xor_ln896_19_fu_514_p2 & p_Result_32_fu_489_p3);

assign deleted_ones_fu_572_p2 = (or_ln890_fu_566_p2 & Range2_all_ones_fu_526_p3);

assign deleted_zeros_fu_546_p2 = (or_ln888_fu_540_p2 ^ Range2_all_ones_fu_526_p3);

assign icmp_ln172_fu_186_p2 = ((indvar_flatten53_fu_108 == 12'd2048) ? 1'b1 : 1'b0);

assign icmp_ln173_fu_213_p2 = ((indvar_flatten38_fu_100 == 9'd128) ? 1'b1 : 1'b0);

assign icmp_ln175_1_fu_426_p2 = ((add_ln175_reg_730 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln175_fu_249_p2 = ((sequence_fu_92 == 4'd8) ? 1'b1 : 1'b0);

assign key_V_address0 = zext_ln837_fu_311_p1;

assign key_value_V_address0 = key_value_V_addr_reg_755;

assign key_value_V_d0 = sum_V_reg_760;

assign lhs_5_fu_445_p3 = {{select_ln173_2_fu_438_p3}, {16'd0}};

assign or_ln173_fu_267_p2 = (icmp_ln173_fu_213_p2 | and_ln172_fu_255_p2);

assign or_ln346_fu_640_p2 = (underflow_fu_626_p2 | overflow_fu_602_p2);

assign or_ln888_fu_540_p2 = (xor_ln888_fu_534_p2 | p_Result_33_fu_506_p3);

assign or_ln890_fu_566_p2 = (xor_ln890_fu_560_p2 | or_ln888_fu_540_p2);

assign or_ln895_fu_590_p2 = (xor_ln895_fu_584_p2 | p_Result_33_fu_506_p3);

assign or_ln896_fu_614_p2 = (xor_ln896_fu_608_p2 | xor_ln896_19_fu_514_p2);

assign overflow_fu_602_p2 = (xor_ln895_13_fu_596_p2 & or_ln895_fu_590_p2);

assign p_Result_32_fu_489_p3 = add_ln1347_8_fu_466_p2[32'd43];

assign p_Result_33_fu_506_p3 = sum_V_12_fu_500_p2[32'd27];

assign p_Result_s_fu_471_p3 = ret_V_fu_460_p2[32'd44];

assign r_V_9_fu_388_p3 = {{key_V_q0}, {6'd0}};

assign ret_V_fu_460_p2 = ($signed(sext_ln1347_fu_453_p1) + $signed(sext_ln1347_12_fu_457_p1));

assign select_ln172_1_fu_227_p3 = ((icmp_ln173_fu_213_p2[0:0] == 1'b1) ? add_ln172_fu_207_p2 : key_feature_fu_104);

assign select_ln172_fu_219_p3 = ((icmp_ln173_fu_213_p2[0:0] == 1'b1) ? 5'd0 : value_feature_fu_96);

assign select_ln173_1_fu_285_p3 = ((and_ln172_fu_255_p2[0:0] == 1'b1) ? add_ln173_fu_261_p2 : select_ln172_fu_219_p3);

assign select_ln173_2_fu_438_p3 = ((or_ln173_reg_710_pp0_iter2_reg[0:0] == 1'b1) ? 28'd0 : lhs_fu_88);

assign select_ln173_3_fu_339_p3 = ((icmp_ln173_fu_213_p2[0:0] == 1'b1) ? 9'd1 : add_ln173_1_fu_333_p2);

assign select_ln173_fu_273_p3 = ((or_ln173_fu_267_p2[0:0] == 1'b1) ? 4'd0 : sequence_fu_92);

assign select_ln346_fu_632_p3 = ((overflow_fu_602_p2[0:0] == 1'b1) ? 28'd134217727 : 28'd134217728);

assign sext_ln1347_12_fu_457_p1 = r_V_reg_740;

assign sext_ln1347_fu_453_p1 = lhs_5_fu_445_p3;

assign shl_ln838_7_fu_396_p3 = {{value_V_q0}, {6'd0}};

assign sum_V_11_fu_479_p4 = {{add_ln1347_8_fu_466_p2[43:16]}};

assign sum_V_12_fu_500_p2 = (zext_ln377_fu_497_p1 + sum_V_11_fu_479_p4);

assign sum_V_fu_646_p3 = ((or_ln346_fu_640_p2[0:0] == 1'b1) ? select_ln346_fu_632_p3 : sum_V_12_fu_500_p2);

assign tmp_43_fu_552_p3 = ret_V_fu_460_p2[32'd44];

assign tmp_8_fu_297_p3 = {{trunc_ln173_fu_281_p1}, {4'd0}};

assign tmp_s_fu_372_p3 = {{trunc_ln172_reg_705}, {4'd0}};

assign trunc_ln172_fu_235_p1 = select_ln172_1_fu_227_p3[3:0];

assign trunc_ln173_fu_281_p1 = select_ln173_fu_273_p3[2:0];

assign underflow_fu_626_p2 = (xor_ln896_20_fu_620_p2 & p_Result_s_fu_471_p3);

assign value_V_address0 = zext_ln837_13_fu_322_p1;

assign xor_ln172_fu_243_p2 = (icmp_ln173_fu_213_p2 ^ 1'd1);

assign xor_ln888_fu_534_p2 = (p_Result_32_fu_489_p3 ^ 1'd1);

assign xor_ln890_fu_560_p2 = (tmp_43_fu_552_p3 ^ 1'd1);

assign xor_ln895_13_fu_596_p2 = (p_Result_s_fu_471_p3 ^ 1'd1);

assign xor_ln895_fu_584_p2 = (deleted_zeros_fu_546_p2 ^ 1'd1);

assign xor_ln896_19_fu_514_p2 = (p_Result_33_fu_506_p3 ^ 1'd1);

assign xor_ln896_20_fu_620_p2 = (or_ln896_fu_614_p2 ^ and_ln891_fu_578_p2);

assign xor_ln896_fu_608_p2 = (deleted_ones_fu_572_p2 ^ 1'd1);

assign zext_ln180_1_fu_293_p1 = select_ln173_1_fu_285_p3;

assign zext_ln180_2_fu_379_p1 = select_ln173_1_reg_715;

assign zext_ln180_3_fu_434_p1 = add_ln180_reg_735;

assign zext_ln180_fu_239_p1 = select_ln172_1_fu_227_p3;

assign zext_ln377_fu_497_p1 = tmp_reg_746;

assign zext_ln837_13_fu_322_p1 = add_ln837_4_fu_316_p2;

assign zext_ln837_fu_311_p1 = add_ln837_fu_305_p2;

endmodule //unsw_linear_transformer_unsw_linear_transformer_Pipeline_VITIS_LOOP_172_15_VITIS_LOOP_173_16_VITIS_LOOP_s
